from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.batch_preprocess_response_results_inner import BatchPreprocessResponseResultsInner
from ensemble_inference.models.operation_status import OperationStatus
from ensemble_inference import util

from ensemble_inference.models.batch_preprocess_response_results_inner import BatchPreprocessResponseResultsInner  # noqa: E501
from ensemble_inference.models.operation_status import OperationStatus  # noqa: E501

class BatchPreprocessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, batch_size=None, successful=None, processing_time_seconds=None, results=None):  # noqa: E501
        """BatchPreprocessResponse - a model defined in OpenAPI

        :param status: The status of this BatchPreprocessResponse.  # noqa: E501
        :type status: OperationStatus
        :param batch_size: The batch_size of this BatchPreprocessResponse.  # noqa: E501
        :type batch_size: int
        :param successful: The successful of this BatchPreprocessResponse.  # noqa: E501
        :type successful: int
        :param processing_time_seconds: The processing_time_seconds of this BatchPreprocessResponse.  # noqa: E501
        :type processing_time_seconds: float
        :param results: The results of this BatchPreprocessResponse.  # noqa: E501
        :type results: List[BatchPreprocessResponseResultsInner]
        """
        self.openapi_types = {
            'status': OperationStatus,
            'batch_size': int,
            'successful': int,
            'processing_time_seconds': float,
            'results': List[BatchPreprocessResponseResultsInner]
        }

        self.attribute_map = {
            'status': 'status',
            'batch_size': 'batch_size',
            'successful': 'successful',
            'processing_time_seconds': 'processing_time_seconds',
            'results': 'results'
        }

        self._status = status
        self._batch_size = batch_size
        self._successful = successful
        self._processing_time_seconds = processing_time_seconds
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'BatchPreprocessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchPreprocessResponse of this BatchPreprocessResponse.  # noqa: E501
        :rtype: BatchPreprocessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> OperationStatus:
        """Gets the status of this BatchPreprocessResponse.


        :return: The status of this BatchPreprocessResponse.
        :rtype: OperationStatus
        """
        return self._status

    @status.setter
    def status(self, status: OperationStatus):
        """Sets the status of this BatchPreprocessResponse.


        :param status: The status of this BatchPreprocessResponse.
        :type status: OperationStatus
        """

        self._status = status

    @property
    def batch_size(self) -> int:
        """Gets the batch_size of this BatchPreprocessResponse.


        :return: The batch_size of this BatchPreprocessResponse.
        :rtype: int
        """
        return self._batch_size

    @batch_size.setter
    def batch_size(self, batch_size: int):
        """Sets the batch_size of this BatchPreprocessResponse.


        :param batch_size: The batch_size of this BatchPreprocessResponse.
        :type batch_size: int
        """

        self._batch_size = batch_size

    @property
    def successful(self) -> int:
        """Gets the successful of this BatchPreprocessResponse.


        :return: The successful of this BatchPreprocessResponse.
        :rtype: int
        """
        return self._successful

    @successful.setter
    def successful(self, successful: int):
        """Sets the successful of this BatchPreprocessResponse.


        :param successful: The successful of this BatchPreprocessResponse.
        :type successful: int
        """

        self._successful = successful

    @property
    def processing_time_seconds(self) -> float:
        """Gets the processing_time_seconds of this BatchPreprocessResponse.


        :return: The processing_time_seconds of this BatchPreprocessResponse.
        :rtype: float
        """
        return self._processing_time_seconds

    @processing_time_seconds.setter
    def processing_time_seconds(self, processing_time_seconds: float):
        """Sets the processing_time_seconds of this BatchPreprocessResponse.


        :param processing_time_seconds: The processing_time_seconds of this BatchPreprocessResponse.
        :type processing_time_seconds: float
        """

        self._processing_time_seconds = processing_time_seconds

    @property
    def results(self) -> List[BatchPreprocessResponseResultsInner]:
        """Gets the results of this BatchPreprocessResponse.


        :return: The results of this BatchPreprocessResponse.
        :rtype: List[BatchPreprocessResponseResultsInner]
        """
        return self._results

    @results.setter
    def results(self, results: List[BatchPreprocessResponseResultsInner]):
        """Sets the results of this BatchPreprocessResponse.


        :param results: The results of this BatchPreprocessResponse.
        :type results: List[BatchPreprocessResponseResultsInner]
        """

        self._results = results
