from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.batch_details import BatchDetails
from ensemble_inference.models.batch_image_result import BatchImageResult
from ensemble_inference.models.batch_process_response_metadata import BatchProcessResponseMetadata
from ensemble_inference.models.batch_process_response_total_processing_times import BatchProcessResponseTotalProcessingTimes
from ensemble_inference.models.cache_stats import CacheStats
from ensemble_inference import util

from ensemble_inference.models.batch_details import BatchDetails  # noqa: E501
from ensemble_inference.models.batch_image_result import BatchImageResult  # noqa: E501
from ensemble_inference.models.batch_process_response_metadata import BatchProcessResponseMetadata  # noqa: E501
from ensemble_inference.models.batch_process_response_total_processing_times import BatchProcessResponseTotalProcessingTimes  # noqa: E501
from ensemble_inference.models.cache_stats import CacheStats  # noqa: E501

class BatchProcessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, request_id=None, timestamp_utc=None, batch_details=None, cache_stats=None, total_processing_times=None, metadata=None, results=None):  # noqa: E501
        """BatchProcessResponse - a model defined in OpenAPI

        :param status: The status of this BatchProcessResponse.  # noqa: E501
        :type status: str
        :param request_id: The request_id of this BatchProcessResponse.  # noqa: E501
        :type request_id: str
        :param timestamp_utc: The timestamp_utc of this BatchProcessResponse.  # noqa: E501
        :type timestamp_utc: datetime
        :param batch_details: The batch_details of this BatchProcessResponse.  # noqa: E501
        :type batch_details: BatchDetails
        :param cache_stats: The cache_stats of this BatchProcessResponse.  # noqa: E501
        :type cache_stats: CacheStats
        :param total_processing_times: The total_processing_times of this BatchProcessResponse.  # noqa: E501
        :type total_processing_times: BatchProcessResponseTotalProcessingTimes
        :param metadata: The metadata of this BatchProcessResponse.  # noqa: E501
        :type metadata: BatchProcessResponseMetadata
        :param results: The results of this BatchProcessResponse.  # noqa: E501
        :type results: List[BatchImageResult]
        """
        self.openapi_types = {
            'status': str,
            'request_id': str,
            'timestamp_utc': datetime,
            'batch_details': BatchDetails,
            'cache_stats': CacheStats,
            'total_processing_times': BatchProcessResponseTotalProcessingTimes,
            'metadata': BatchProcessResponseMetadata,
            'results': List[BatchImageResult]
        }

        self.attribute_map = {
            'status': 'status',
            'request_id': 'request_id',
            'timestamp_utc': 'timestamp_utc',
            'batch_details': 'batch_details',
            'cache_stats': 'cache_stats',
            'total_processing_times': 'total_processing_times',
            'metadata': 'metadata',
            'results': 'results'
        }

        self._status = status
        self._request_id = request_id
        self._timestamp_utc = timestamp_utc
        self._batch_details = batch_details
        self._cache_stats = cache_stats
        self._total_processing_times = total_processing_times
        self._metadata = metadata
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'BatchProcessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchProcessResponse of this BatchProcessResponse.  # noqa: E501
        :rtype: BatchProcessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this BatchProcessResponse.


        :return: The status of this BatchProcessResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this BatchProcessResponse.


        :param status: The status of this BatchProcessResponse.
        :type status: str
        """
        allowed_values = ["SUCCESS"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def request_id(self) -> str:
        """Gets the request_id of this BatchProcessResponse.

        Unique batch request identifier  # noqa: E501

        :return: The request_id of this BatchProcessResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this BatchProcessResponse.

        Unique batch request identifier  # noqa: E501

        :param request_id: The request_id of this BatchProcessResponse.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def timestamp_utc(self) -> datetime:
        """Gets the timestamp_utc of this BatchProcessResponse.


        :return: The timestamp_utc of this BatchProcessResponse.
        :rtype: datetime
        """
        return self._timestamp_utc

    @timestamp_utc.setter
    def timestamp_utc(self, timestamp_utc: datetime):
        """Sets the timestamp_utc of this BatchProcessResponse.


        :param timestamp_utc: The timestamp_utc of this BatchProcessResponse.
        :type timestamp_utc: datetime
        """
        if timestamp_utc is None:
            raise ValueError("Invalid value for `timestamp_utc`, must not be `None`")  # noqa: E501

        self._timestamp_utc = timestamp_utc

    @property
    def batch_details(self) -> BatchDetails:
        """Gets the batch_details of this BatchProcessResponse.


        :return: The batch_details of this BatchProcessResponse.
        :rtype: BatchDetails
        """
        return self._batch_details

    @batch_details.setter
    def batch_details(self, batch_details: BatchDetails):
        """Sets the batch_details of this BatchProcessResponse.


        :param batch_details: The batch_details of this BatchProcessResponse.
        :type batch_details: BatchDetails
        """
        if batch_details is None:
            raise ValueError("Invalid value for `batch_details`, must not be `None`")  # noqa: E501

        self._batch_details = batch_details

    @property
    def cache_stats(self) -> CacheStats:
        """Gets the cache_stats of this BatchProcessResponse.


        :return: The cache_stats of this BatchProcessResponse.
        :rtype: CacheStats
        """
        return self._cache_stats

    @cache_stats.setter
    def cache_stats(self, cache_stats: CacheStats):
        """Sets the cache_stats of this BatchProcessResponse.


        :param cache_stats: The cache_stats of this BatchProcessResponse.
        :type cache_stats: CacheStats
        """
        if cache_stats is None:
            raise ValueError("Invalid value for `cache_stats`, must not be `None`")  # noqa: E501

        self._cache_stats = cache_stats

    @property
    def total_processing_times(self) -> BatchProcessResponseTotalProcessingTimes:
        """Gets the total_processing_times of this BatchProcessResponse.


        :return: The total_processing_times of this BatchProcessResponse.
        :rtype: BatchProcessResponseTotalProcessingTimes
        """
        return self._total_processing_times

    @total_processing_times.setter
    def total_processing_times(self, total_processing_times: BatchProcessResponseTotalProcessingTimes):
        """Sets the total_processing_times of this BatchProcessResponse.


        :param total_processing_times: The total_processing_times of this BatchProcessResponse.
        :type total_processing_times: BatchProcessResponseTotalProcessingTimes
        """
        if total_processing_times is None:
            raise ValueError("Invalid value for `total_processing_times`, must not be `None`")  # noqa: E501

        self._total_processing_times = total_processing_times

    @property
    def metadata(self) -> BatchProcessResponseMetadata:
        """Gets the metadata of this BatchProcessResponse.


        :return: The metadata of this BatchProcessResponse.
        :rtype: BatchProcessResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: BatchProcessResponseMetadata):
        """Sets the metadata of this BatchProcessResponse.


        :param metadata: The metadata of this BatchProcessResponse.
        :type metadata: BatchProcessResponseMetadata
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    @property
    def results(self) -> List[BatchImageResult]:
        """Gets the results of this BatchProcessResponse.


        :return: The results of this BatchProcessResponse.
        :rtype: List[BatchImageResult]
        """
        return self._results

    @results.setter
    def results(self, results: List[BatchImageResult]):
        """Sets the results of this BatchProcessResponse.


        :param results: The results of this BatchProcessResponse.
        :type results: List[BatchImageResult]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results
