from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class BatchProcessResponseTotalProcessingTimes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, preprocessing_ms=None, inference_ms=None, total_ms=None, per_image_ms=None):  # noqa: E501
        """BatchProcessResponseTotalProcessingTimes - a model defined in OpenAPI

        :param preprocessing_ms: The preprocessing_ms of this BatchProcessResponseTotalProcessingTimes.  # noqa: E501
        :type preprocessing_ms: float
        :param inference_ms: The inference_ms of this BatchProcessResponseTotalProcessingTimes.  # noqa: E501
        :type inference_ms: float
        :param total_ms: The total_ms of this BatchProcessResponseTotalProcessingTimes.  # noqa: E501
        :type total_ms: float
        :param per_image_ms: The per_image_ms of this BatchProcessResponseTotalProcessingTimes.  # noqa: E501
        :type per_image_ms: float
        """
        self.openapi_types = {
            'preprocessing_ms': float,
            'inference_ms': float,
            'total_ms': float,
            'per_image_ms': float
        }

        self.attribute_map = {
            'preprocessing_ms': 'preprocessing_ms',
            'inference_ms': 'inference_ms',
            'total_ms': 'total_ms',
            'per_image_ms': 'per_image_ms'
        }

        self._preprocessing_ms = preprocessing_ms
        self._inference_ms = inference_ms
        self._total_ms = total_ms
        self._per_image_ms = per_image_ms

    @classmethod
    def from_dict(cls, dikt) -> 'BatchProcessResponseTotalProcessingTimes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchProcessResponse_total_processing_times of this BatchProcessResponseTotalProcessingTimes.  # noqa: E501
        :rtype: BatchProcessResponseTotalProcessingTimes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preprocessing_ms(self) -> float:
        """Gets the preprocessing_ms of this BatchProcessResponseTotalProcessingTimes.


        :return: The preprocessing_ms of this BatchProcessResponseTotalProcessingTimes.
        :rtype: float
        """
        return self._preprocessing_ms

    @preprocessing_ms.setter
    def preprocessing_ms(self, preprocessing_ms: float):
        """Sets the preprocessing_ms of this BatchProcessResponseTotalProcessingTimes.


        :param preprocessing_ms: The preprocessing_ms of this BatchProcessResponseTotalProcessingTimes.
        :type preprocessing_ms: float
        """

        self._preprocessing_ms = preprocessing_ms

    @property
    def inference_ms(self) -> float:
        """Gets the inference_ms of this BatchProcessResponseTotalProcessingTimes.


        :return: The inference_ms of this BatchProcessResponseTotalProcessingTimes.
        :rtype: float
        """
        return self._inference_ms

    @inference_ms.setter
    def inference_ms(self, inference_ms: float):
        """Sets the inference_ms of this BatchProcessResponseTotalProcessingTimes.


        :param inference_ms: The inference_ms of this BatchProcessResponseTotalProcessingTimes.
        :type inference_ms: float
        """

        self._inference_ms = inference_ms

    @property
    def total_ms(self) -> float:
        """Gets the total_ms of this BatchProcessResponseTotalProcessingTimes.


        :return: The total_ms of this BatchProcessResponseTotalProcessingTimes.
        :rtype: float
        """
        return self._total_ms

    @total_ms.setter
    def total_ms(self, total_ms: float):
        """Sets the total_ms of this BatchProcessResponseTotalProcessingTimes.


        :param total_ms: The total_ms of this BatchProcessResponseTotalProcessingTimes.
        :type total_ms: float
        """

        self._total_ms = total_ms

    @property
    def per_image_ms(self) -> float:
        """Gets the per_image_ms of this BatchProcessResponseTotalProcessingTimes.


        :return: The per_image_ms of this BatchProcessResponseTotalProcessingTimes.
        :rtype: float
        """
        return self._per_image_ms

    @per_image_ms.setter
    def per_image_ms(self, per_image_ms: float):
        """Sets the per_image_ms of this BatchProcessResponseTotalProcessingTimes.


        :param per_image_ms: The per_image_ms of this BatchProcessResponseTotalProcessingTimes.
        :type per_image_ms: float
        """

        self._per_image_ms = per_image_ms
