from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.model_configuration import ModelConfiguration
from ensemble_inference.models.version_info import VersionInfo
from ensemble_inference import util

from ensemble_inference.models.model_configuration import ModelConfiguration  # noqa: E501
from ensemble_inference.models.version_info import VersionInfo  # noqa: E501

class BatchMetadataMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version_info=None, model_configuration=None):  # noqa: E501
        """BatchMetadataMetadata - a model defined in OpenAPI

        :param version_info: The version_info of this BatchMetadataMetadata.  # noqa: E501
        :type version_info: VersionInfo
        :param model_configuration: The model_configuration of this BatchMetadataMetadata.  # noqa: E501
        :type model_configuration: ModelConfiguration
        """
        self.openapi_types = {
            'version_info': VersionInfo,
            'model_configuration': ModelConfiguration
        }

        self.attribute_map = {
            'version_info': 'version_info',
            'model_configuration': 'model_configuration'
        }

        self._version_info = version_info
        self._model_configuration = model_configuration

    @classmethod
    def from_dict(cls, dikt) -> 'BatchMetadataMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchMetadata_metadata of this BatchMetadataMetadata.  # noqa: E501
        :rtype: BatchMetadataMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version_info(self) -> VersionInfo:
        """Gets the version_info of this BatchMetadataMetadata.


        :return: The version_info of this BatchMetadataMetadata.
        :rtype: VersionInfo
        """
        return self._version_info

    @version_info.setter
    def version_info(self, version_info: VersionInfo):
        """Sets the version_info of this BatchMetadataMetadata.


        :param version_info: The version_info of this BatchMetadataMetadata.
        :type version_info: VersionInfo
        """
        if version_info is None:
            raise ValueError("Invalid value for `version_info`, must not be `None`")  # noqa: E501

        self._version_info = version_info

    @property
    def model_configuration(self) -> ModelConfiguration:
        """Gets the model_configuration of this BatchMetadataMetadata.


        :return: The model_configuration of this BatchMetadataMetadata.
        :rtype: ModelConfiguration
        """
        return self._model_configuration

    @model_configuration.setter
    def model_configuration(self, model_configuration: ModelConfiguration):
        """Sets the model_configuration of this BatchMetadataMetadata.


        :param model_configuration: The model_configuration of this BatchMetadataMetadata.
        :type model_configuration: ModelConfiguration
        """

        self._model_configuration = model_configuration
