from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.batch_details import BatchDetails
from ensemble_inference.models.batch_metadata_metadata import BatchMetadataMetadata
from ensemble_inference.models.batch_metadata_total_processing_times import BatchMetadataTotalProcessingTimes
from ensemble_inference.models.cache_stats import CacheStats
from ensemble_inference.models.operation_status import OperationStatus
from ensemble_inference import util

from ensemble_inference.models.batch_details import BatchDetails  # noqa: E501
from ensemble_inference.models.batch_metadata_metadata import BatchMetadataMetadata  # noqa: E501
from ensemble_inference.models.batch_metadata_total_processing_times import BatchMetadataTotalProcessingTimes  # noqa: E501
from ensemble_inference.models.cache_stats import CacheStats  # noqa: E501
from ensemble_inference.models.operation_status import OperationStatus  # noqa: E501

class BatchMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_id=None, timestamp_utc=None, status=None, batch_details=None, cache_stats=None, total_processing_times=None, metadata=None):  # noqa: E501
        """BatchMetadata - a model defined in OpenAPI

        :param request_id: The request_id of this BatchMetadata.  # noqa: E501
        :type request_id: str
        :param timestamp_utc: The timestamp_utc of this BatchMetadata.  # noqa: E501
        :type timestamp_utc: datetime
        :param status: The status of this BatchMetadata.  # noqa: E501
        :type status: OperationStatus
        :param batch_details: The batch_details of this BatchMetadata.  # noqa: E501
        :type batch_details: BatchDetails
        :param cache_stats: The cache_stats of this BatchMetadata.  # noqa: E501
        :type cache_stats: CacheStats
        :param total_processing_times: The total_processing_times of this BatchMetadata.  # noqa: E501
        :type total_processing_times: BatchMetadataTotalProcessingTimes
        :param metadata: The metadata of this BatchMetadata.  # noqa: E501
        :type metadata: BatchMetadataMetadata
        """
        self.openapi_types = {
            'request_id': str,
            'timestamp_utc': datetime,
            'status': OperationStatus,
            'batch_details': BatchDetails,
            'cache_stats': CacheStats,
            'total_processing_times': BatchMetadataTotalProcessingTimes,
            'metadata': BatchMetadataMetadata
        }

        self.attribute_map = {
            'request_id': 'request_id',
            'timestamp_utc': 'timestamp_utc',
            'status': 'status',
            'batch_details': 'batch_details',
            'cache_stats': 'cache_stats',
            'total_processing_times': 'total_processing_times',
            'metadata': 'metadata'
        }

        self._request_id = request_id
        self._timestamp_utc = timestamp_utc
        self._status = status
        self._batch_details = batch_details
        self._cache_stats = cache_stats
        self._total_processing_times = total_processing_times
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'BatchMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchMetadata of this BatchMetadata.  # noqa: E501
        :rtype: BatchMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self) -> str:
        """Gets the request_id of this BatchMetadata.

        Unique batch request identifier  # noqa: E501

        :return: The request_id of this BatchMetadata.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this BatchMetadata.

        Unique batch request identifier  # noqa: E501

        :param request_id: The request_id of this BatchMetadata.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def timestamp_utc(self) -> datetime:
        """Gets the timestamp_utc of this BatchMetadata.

        UTC timestamp in ISO 8601 format  # noqa: E501

        :return: The timestamp_utc of this BatchMetadata.
        :rtype: datetime
        """
        return self._timestamp_utc

    @timestamp_utc.setter
    def timestamp_utc(self, timestamp_utc: datetime):
        """Sets the timestamp_utc of this BatchMetadata.

        UTC timestamp in ISO 8601 format  # noqa: E501

        :param timestamp_utc: The timestamp_utc of this BatchMetadata.
        :type timestamp_utc: datetime
        """
        if timestamp_utc is None:
            raise ValueError("Invalid value for `timestamp_utc`, must not be `None`")  # noqa: E501

        self._timestamp_utc = timestamp_utc

    @property
    def status(self) -> OperationStatus:
        """Gets the status of this BatchMetadata.


        :return: The status of this BatchMetadata.
        :rtype: OperationStatus
        """
        return self._status

    @status.setter
    def status(self, status: OperationStatus):
        """Sets the status of this BatchMetadata.


        :param status: The status of this BatchMetadata.
        :type status: OperationStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def batch_details(self) -> BatchDetails:
        """Gets the batch_details of this BatchMetadata.


        :return: The batch_details of this BatchMetadata.
        :rtype: BatchDetails
        """
        return self._batch_details

    @batch_details.setter
    def batch_details(self, batch_details: BatchDetails):
        """Sets the batch_details of this BatchMetadata.


        :param batch_details: The batch_details of this BatchMetadata.
        :type batch_details: BatchDetails
        """
        if batch_details is None:
            raise ValueError("Invalid value for `batch_details`, must not be `None`")  # noqa: E501

        self._batch_details = batch_details

    @property
    def cache_stats(self) -> CacheStats:
        """Gets the cache_stats of this BatchMetadata.


        :return: The cache_stats of this BatchMetadata.
        :rtype: CacheStats
        """
        return self._cache_stats

    @cache_stats.setter
    def cache_stats(self, cache_stats: CacheStats):
        """Sets the cache_stats of this BatchMetadata.


        :param cache_stats: The cache_stats of this BatchMetadata.
        :type cache_stats: CacheStats
        """
        if cache_stats is None:
            raise ValueError("Invalid value for `cache_stats`, must not be `None`")  # noqa: E501

        self._cache_stats = cache_stats

    @property
    def total_processing_times(self) -> BatchMetadataTotalProcessingTimes:
        """Gets the total_processing_times of this BatchMetadata.


        :return: The total_processing_times of this BatchMetadata.
        :rtype: BatchMetadataTotalProcessingTimes
        """
        return self._total_processing_times

    @total_processing_times.setter
    def total_processing_times(self, total_processing_times: BatchMetadataTotalProcessingTimes):
        """Sets the total_processing_times of this BatchMetadata.


        :param total_processing_times: The total_processing_times of this BatchMetadata.
        :type total_processing_times: BatchMetadataTotalProcessingTimes
        """
        if total_processing_times is None:
            raise ValueError("Invalid value for `total_processing_times`, must not be `None`")  # noqa: E501

        self._total_processing_times = total_processing_times

    @property
    def metadata(self) -> BatchMetadataMetadata:
        """Gets the metadata of this BatchMetadata.


        :return: The metadata of this BatchMetadata.
        :rtype: BatchMetadataMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: BatchMetadataMetadata):
        """Sets the metadata of this BatchMetadata.


        :param metadata: The metadata of this BatchMetadata.
        :type metadata: BatchMetadataMetadata
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata
