from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class BatchDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, batch_size=None, processed_successfully=None, processed_failure=None):  # noqa: E501
        """BatchDetails - a model defined in OpenAPI

        :param batch_size: The batch_size of this BatchDetails.  # noqa: E501
        :type batch_size: int
        :param processed_successfully: The processed_successfully of this BatchDetails.  # noqa: E501
        :type processed_successfully: int
        :param processed_failure: The processed_failure of this BatchDetails.  # noqa: E501
        :type processed_failure: int
        """
        self.openapi_types = {
            'batch_size': int,
            'processed_successfully': int,
            'processed_failure': int
        }

        self.attribute_map = {
            'batch_size': 'batch_size',
            'processed_successfully': 'processed_successfully',
            'processed_failure': 'processed_failure'
        }

        self._batch_size = batch_size
        self._processed_successfully = processed_successfully
        self._processed_failure = processed_failure

    @classmethod
    def from_dict(cls, dikt) -> 'BatchDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchDetails of this BatchDetails.  # noqa: E501
        :rtype: BatchDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def batch_size(self) -> int:
        """Gets the batch_size of this BatchDetails.


        :return: The batch_size of this BatchDetails.
        :rtype: int
        """
        return self._batch_size

    @batch_size.setter
    def batch_size(self, batch_size: int):
        """Sets the batch_size of this BatchDetails.


        :param batch_size: The batch_size of this BatchDetails.
        :type batch_size: int
        """
        if batch_size is None:
            raise ValueError("Invalid value for `batch_size`, must not be `None`")  # noqa: E501

        self._batch_size = batch_size

    @property
    def processed_successfully(self) -> int:
        """Gets the processed_successfully of this BatchDetails.


        :return: The processed_successfully of this BatchDetails.
        :rtype: int
        """
        return self._processed_successfully

    @processed_successfully.setter
    def processed_successfully(self, processed_successfully: int):
        """Sets the processed_successfully of this BatchDetails.


        :param processed_successfully: The processed_successfully of this BatchDetails.
        :type processed_successfully: int
        """
        if processed_successfully is None:
            raise ValueError("Invalid value for `processed_successfully`, must not be `None`")  # noqa: E501

        self._processed_successfully = processed_successfully

    @property
    def processed_failure(self) -> int:
        """Gets the processed_failure of this BatchDetails.


        :return: The processed_failure of this BatchDetails.
        :rtype: int
        """
        return self._processed_failure

    @processed_failure.setter
    def processed_failure(self, processed_failure: int):
        """Sets the processed_failure of this BatchDetails.


        :param processed_failure: The processed_failure of this BatchDetails.
        :type processed_failure: int
        """
        if processed_failure is None:
            raise ValueError("Invalid value for `processed_failure`, must not be `None`")  # noqa: E501

        self._processed_failure = processed_failure
