from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class BatchProcessingMetrics(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, batch_id=None, batch_wait_ms=None, batch_execution_ms=None, batch_total_ms=None, batch_size=None):  # noqa: E501
        """BatchProcessingMetrics - a model defined in OpenAPI

        :param batch_id: The batch_id of this BatchProcessingMetrics.  # noqa: E501
        :type batch_id: str
        :param batch_wait_ms: The batch_wait_ms of this BatchProcessingMetrics.  # noqa: E501
        :type batch_wait_ms: float
        :param batch_execution_ms: The batch_execution_ms of this BatchProcessingMetrics.  # noqa: E501
        :type batch_execution_ms: float
        :param batch_total_ms: The batch_total_ms of this BatchProcessingMetrics.  # noqa: E501
        :type batch_total_ms: float
        :param batch_size: The batch_size of this BatchProcessingMetrics.  # noqa: E501
        :type batch_size: int
        """
        self.openapi_types = {
            'batch_id': str,
            'batch_wait_ms': float,
            'batch_execution_ms': float,
            'batch_total_ms': float,
            'batch_size': int
        }

        self.attribute_map = {
            'batch_id': 'batch_id',
            'batch_wait_ms': 'batch_wait_ms',
            'batch_execution_ms': 'batch_execution_ms',
            'batch_total_ms': 'batch_total_ms',
            'batch_size': 'batch_size'
        }

        self._batch_id = batch_id
        self._batch_wait_ms = batch_wait_ms
        self._batch_execution_ms = batch_execution_ms
        self._batch_total_ms = batch_total_ms
        self._batch_size = batch_size

    @classmethod
    def from_dict(cls, dikt) -> 'BatchProcessingMetrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchProcessingMetrics of this BatchProcessingMetrics.  # noqa: E501
        :rtype: BatchProcessingMetrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def batch_id(self) -> str:
        """Gets the batch_id of this BatchProcessingMetrics.

        Unique identifier for the executed dynamic batch  # noqa: E501

        :return: The batch_id of this BatchProcessingMetrics.
        :rtype: str
        """
        return self._batch_id

    @batch_id.setter
    def batch_id(self, batch_id: str):
        """Sets the batch_id of this BatchProcessingMetrics.

        Unique identifier for the executed dynamic batch  # noqa: E501

        :param batch_id: The batch_id of this BatchProcessingMetrics.
        :type batch_id: str
        """

        self._batch_id = batch_id

    @property
    def batch_wait_ms(self) -> float:
        """Gets the batch_wait_ms of this BatchProcessingMetrics.

        Time spent waiting in the dynamic batch queue before inference starts  # noqa: E501

        :return: The batch_wait_ms of this BatchProcessingMetrics.
        :rtype: float
        """
        return self._batch_wait_ms

    @batch_wait_ms.setter
    def batch_wait_ms(self, batch_wait_ms: float):
        """Sets the batch_wait_ms of this BatchProcessingMetrics.

        Time spent waiting in the dynamic batch queue before inference starts  # noqa: E501

        :param batch_wait_ms: The batch_wait_ms of this BatchProcessingMetrics.
        :type batch_wait_ms: float
        """

        self._batch_wait_ms = batch_wait_ms

    @property
    def batch_execution_ms(self) -> float:
        """Gets the batch_execution_ms of this BatchProcessingMetrics.

        Time spent executing the grouped batch on the model  # noqa: E501

        :return: The batch_execution_ms of this BatchProcessingMetrics.
        :rtype: float
        """
        return self._batch_execution_ms

    @batch_execution_ms.setter
    def batch_execution_ms(self, batch_execution_ms: float):
        """Sets the batch_execution_ms of this BatchProcessingMetrics.

        Time spent executing the grouped batch on the model  # noqa: E501

        :param batch_execution_ms: The batch_execution_ms of this BatchProcessingMetrics.
        :type batch_execution_ms: float
        """

        self._batch_execution_ms = batch_execution_ms

    @property
    def batch_total_ms(self) -> float:
        """Gets the batch_total_ms of this BatchProcessingMetrics.

        Total time from queue enqueue to batch result availability  # noqa: E501

        :return: The batch_total_ms of this BatchProcessingMetrics.
        :rtype: float
        """
        return self._batch_total_ms

    @batch_total_ms.setter
    def batch_total_ms(self, batch_total_ms: float):
        """Sets the batch_total_ms of this BatchProcessingMetrics.

        Total time from queue enqueue to batch result availability  # noqa: E501

        :param batch_total_ms: The batch_total_ms of this BatchProcessingMetrics.
        :type batch_total_ms: float
        """

        self._batch_total_ms = batch_total_ms

    @property
    def batch_size(self) -> int:
        """Gets the batch_size of this BatchProcessingMetrics.

        Number of requests grouped into the executed batch  # noqa: E501

        :return: The batch_size of this BatchProcessingMetrics.
        :rtype: int
        """
        return self._batch_size

    @batch_size.setter
    def batch_size(self, batch_size: int):
        """Sets the batch_size of this BatchProcessingMetrics.

        Number of requests grouped into the executed batch  # noqa: E501

        :param batch_size: The batch_size of this BatchProcessingMetrics.
        :type batch_size: int
        """

        self._batch_size = batch_size
