from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.batch_metadata import BatchMetadata
from ensemble_inference.models.process_result import ProcessResult
from ensemble_inference import util

from ensemble_inference.models.batch_metadata import BatchMetadata  # noqa: E501
from ensemble_inference.models.process_result import ProcessResult  # noqa: E501

class BatchProcessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, batch_metadata=None, batch_result=None):  # noqa: E501
        """BatchProcessResponse - a model defined in OpenAPI

        :param batch_metadata: The batch_metadata of this BatchProcessResponse.  # noqa: E501
        :type batch_metadata: BatchMetadata
        :param batch_result: The batch_result of this BatchProcessResponse.  # noqa: E501
        :type batch_result: List[ProcessResult]
        """
        self.openapi_types = {
            'batch_metadata': BatchMetadata,
            'batch_result': List[ProcessResult]
        }

        self.attribute_map = {
            'batch_metadata': 'batch_metadata',
            'batch_result': 'batch_result'
        }

        self._batch_metadata = batch_metadata
        self._batch_result = batch_result

    @classmethod
    def from_dict(cls, dikt) -> 'BatchProcessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BatchProcessResponse of this BatchProcessResponse.  # noqa: E501
        :rtype: BatchProcessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def batch_metadata(self) -> BatchMetadata:
        """Gets the batch_metadata of this BatchProcessResponse.


        :return: The batch_metadata of this BatchProcessResponse.
        :rtype: BatchMetadata
        """
        return self._batch_metadata

    @batch_metadata.setter
    def batch_metadata(self, batch_metadata: BatchMetadata):
        """Sets the batch_metadata of this BatchProcessResponse.


        :param batch_metadata: The batch_metadata of this BatchProcessResponse.
        :type batch_metadata: BatchMetadata
        """
        if batch_metadata is None:
            raise ValueError("Invalid value for `batch_metadata`, must not be `None`")  # noqa: E501

        self._batch_metadata = batch_metadata

    @property
    def batch_result(self) -> List[ProcessResult]:
        """Gets the batch_result of this BatchProcessResponse.

        Array of processing results for each image in the batch  # noqa: E501

        :return: The batch_result of this BatchProcessResponse.
        :rtype: List[ProcessResult]
        """
        return self._batch_result

    @batch_result.setter
    def batch_result(self, batch_result: List[ProcessResult]):
        """Sets the batch_result of this BatchProcessResponse.

        Array of processing results for each image in the batch  # noqa: E501

        :param batch_result: The batch_result of this BatchProcessResponse.
        :type batch_result: List[ProcessResult]
        """
        if batch_result is None:
            raise ValueError("Invalid value for `batch_result`, must not be `None`")  # noqa: E501

        self._batch_result = batch_result
