from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class CacheStats(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cache_hits=None, cache_misses=None, cached_percentage=None):  # noqa: E501
        """CacheStats - a model defined in OpenAPI

        :param cache_hits: The cache_hits of this CacheStats.  # noqa: E501
        :type cache_hits: int
        :param cache_misses: The cache_misses of this CacheStats.  # noqa: E501
        :type cache_misses: int
        :param cached_percentage: The cached_percentage of this CacheStats.  # noqa: E501
        :type cached_percentage: float
        """
        self.openapi_types = {
            'cache_hits': int,
            'cache_misses': int,
            'cached_percentage': float
        }

        self.attribute_map = {
            'cache_hits': 'cache_hits',
            'cache_misses': 'cache_misses',
            'cached_percentage': 'cached_percentage'
        }

        self._cache_hits = cache_hits
        self._cache_misses = cache_misses
        self._cached_percentage = cached_percentage

    @classmethod
    def from_dict(cls, dikt) -> 'CacheStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CacheStats of this CacheStats.  # noqa: E501
        :rtype: CacheStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cache_hits(self) -> int:
        """Gets the cache_hits of this CacheStats.


        :return: The cache_hits of this CacheStats.
        :rtype: int
        """
        return self._cache_hits

    @cache_hits.setter
    def cache_hits(self, cache_hits: int):
        """Sets the cache_hits of this CacheStats.


        :param cache_hits: The cache_hits of this CacheStats.
        :type cache_hits: int
        """
        if cache_hits is None:
            raise ValueError("Invalid value for `cache_hits`, must not be `None`")  # noqa: E501

        self._cache_hits = cache_hits

    @property
    def cache_misses(self) -> int:
        """Gets the cache_misses of this CacheStats.


        :return: The cache_misses of this CacheStats.
        :rtype: int
        """
        return self._cache_misses

    @cache_misses.setter
    def cache_misses(self, cache_misses: int):
        """Sets the cache_misses of this CacheStats.


        :param cache_misses: The cache_misses of this CacheStats.
        :type cache_misses: int
        """
        if cache_misses is None:
            raise ValueError("Invalid value for `cache_misses`, must not be `None`")  # noqa: E501

        self._cache_misses = cache_misses

    @property
    def cached_percentage(self) -> float:
        """Gets the cached_percentage of this CacheStats.


        :return: The cached_percentage of this CacheStats.
        :rtype: float
        """
        return self._cached_percentage

    @cached_percentage.setter
    def cached_percentage(self, cached_percentage: float):
        """Sets the cached_percentage of this CacheStats.


        :param cached_percentage: The cached_percentage of this CacheStats.
        :type cached_percentage: float
        """
        if cached_percentage is None:
            raise ValueError("Invalid value for `cached_percentage`, must not be `None`")  # noqa: E501

        self._cached_percentage = cached_percentage
