from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class CacheStatsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=None, connected=None, total_keys=None, memory_usage=None, hits=None, misses=None, hit_rate=None):  # noqa: E501
        """CacheStatsResponse - a model defined in OpenAPI

        :param enabled: The enabled of this CacheStatsResponse.  # noqa: E501
        :type enabled: bool
        :param connected: The connected of this CacheStatsResponse.  # noqa: E501
        :type connected: bool
        :param total_keys: The total_keys of this CacheStatsResponse.  # noqa: E501
        :type total_keys: int
        :param memory_usage: The memory_usage of this CacheStatsResponse.  # noqa: E501
        :type memory_usage: str
        :param hits: The hits of this CacheStatsResponse.  # noqa: E501
        :type hits: int
        :param misses: The misses of this CacheStatsResponse.  # noqa: E501
        :type misses: int
        :param hit_rate: The hit_rate of this CacheStatsResponse.  # noqa: E501
        :type hit_rate: float
        """
        self.openapi_types = {
            'enabled': bool,
            'connected': bool,
            'total_keys': int,
            'memory_usage': str,
            'hits': int,
            'misses': int,
            'hit_rate': float
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'connected': 'connected',
            'total_keys': 'total_keys',
            'memory_usage': 'memory_usage',
            'hits': 'hits',
            'misses': 'misses',
            'hit_rate': 'hit_rate'
        }

        self._enabled = enabled
        self._connected = connected
        self._total_keys = total_keys
        self._memory_usage = memory_usage
        self._hits = hits
        self._misses = misses
        self._hit_rate = hit_rate

    @classmethod
    def from_dict(cls, dikt) -> 'CacheStatsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CacheStatsResponse of this CacheStatsResponse.  # noqa: E501
        :rtype: CacheStatsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this CacheStatsResponse.


        :return: The enabled of this CacheStatsResponse.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this CacheStatsResponse.


        :param enabled: The enabled of this CacheStatsResponse.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def connected(self) -> bool:
        """Gets the connected of this CacheStatsResponse.


        :return: The connected of this CacheStatsResponse.
        :rtype: bool
        """
        return self._connected

    @connected.setter
    def connected(self, connected: bool):
        """Sets the connected of this CacheStatsResponse.


        :param connected: The connected of this CacheStatsResponse.
        :type connected: bool
        """

        self._connected = connected

    @property
    def total_keys(self) -> int:
        """Gets the total_keys of this CacheStatsResponse.


        :return: The total_keys of this CacheStatsResponse.
        :rtype: int
        """
        return self._total_keys

    @total_keys.setter
    def total_keys(self, total_keys: int):
        """Sets the total_keys of this CacheStatsResponse.


        :param total_keys: The total_keys of this CacheStatsResponse.
        :type total_keys: int
        """

        self._total_keys = total_keys

    @property
    def memory_usage(self) -> str:
        """Gets the memory_usage of this CacheStatsResponse.


        :return: The memory_usage of this CacheStatsResponse.
        :rtype: str
        """
        return self._memory_usage

    @memory_usage.setter
    def memory_usage(self, memory_usage: str):
        """Sets the memory_usage of this CacheStatsResponse.


        :param memory_usage: The memory_usage of this CacheStatsResponse.
        :type memory_usage: str
        """

        self._memory_usage = memory_usage

    @property
    def hits(self) -> int:
        """Gets the hits of this CacheStatsResponse.


        :return: The hits of this CacheStatsResponse.
        :rtype: int
        """
        return self._hits

    @hits.setter
    def hits(self, hits: int):
        """Sets the hits of this CacheStatsResponse.


        :param hits: The hits of this CacheStatsResponse.
        :type hits: int
        """

        self._hits = hits

    @property
    def misses(self) -> int:
        """Gets the misses of this CacheStatsResponse.


        :return: The misses of this CacheStatsResponse.
        :rtype: int
        """
        return self._misses

    @misses.setter
    def misses(self, misses: int):
        """Sets the misses of this CacheStatsResponse.


        :param misses: The misses of this CacheStatsResponse.
        :type misses: int
        """

        self._misses = misses

    @property
    def hit_rate(self) -> float:
        """Gets the hit_rate of this CacheStatsResponse.


        :return: The hit_rate of this CacheStatsResponse.
        :rtype: float
        """
        return self._hit_rate

    @hit_rate.setter
    def hit_rate(self, hit_rate: float):
        """Sets the hit_rate of this CacheStatsResponse.


        :param hit_rate: The hit_rate of this CacheStatsResponse.
        :type hit_rate: float
        """

        self._hit_rate = hit_rate
