from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class CacheClearResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, message=None, deleted_count=None, pattern=None):  # noqa: E501
        """CacheClearResponse - a model defined in OpenAPI

        :param status: The status of this CacheClearResponse.  # noqa: E501
        :type status: str
        :param message: The message of this CacheClearResponse.  # noqa: E501
        :type message: str
        :param deleted_count: The deleted_count of this CacheClearResponse.  # noqa: E501
        :type deleted_count: int
        :param pattern: The pattern of this CacheClearResponse.  # noqa: E501
        :type pattern: str
        """
        self.openapi_types = {
            'status': str,
            'message': str,
            'deleted_count': int,
            'pattern': str
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'deleted_count': 'deleted_count',
            'pattern': 'pattern'
        }

        self._status = status
        self._message = message
        self._deleted_count = deleted_count
        self._pattern = pattern

    @classmethod
    def from_dict(cls, dikt) -> 'CacheClearResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CacheClearResponse of this CacheClearResponse.  # noqa: E501
        :rtype: CacheClearResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this CacheClearResponse.


        :return: The status of this CacheClearResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this CacheClearResponse.


        :param status: The status of this CacheClearResponse.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this CacheClearResponse.


        :return: The message of this CacheClearResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CacheClearResponse.


        :param message: The message of this CacheClearResponse.
        :type message: str
        """

        self._message = message

    @property
    def deleted_count(self) -> int:
        """Gets the deleted_count of this CacheClearResponse.


        :return: The deleted_count of this CacheClearResponse.
        :rtype: int
        """
        return self._deleted_count

    @deleted_count.setter
    def deleted_count(self, deleted_count: int):
        """Sets the deleted_count of this CacheClearResponse.


        :param deleted_count: The deleted_count of this CacheClearResponse.
        :type deleted_count: int
        """

        self._deleted_count = deleted_count

    @property
    def pattern(self) -> str:
        """Gets the pattern of this CacheClearResponse.


        :return: The pattern of this CacheClearResponse.
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern: str):
        """Sets the pattern of this CacheClearResponse.


        :param pattern: The pattern of this CacheClearResponse.
        :type pattern: str
        """

        self._pattern = pattern
