from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class CacheHealthResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=None, connected=None, status=None, response_time_ms=None):  # noqa: E501
        """CacheHealthResponse - a model defined in OpenAPI

        :param enabled: The enabled of this CacheHealthResponse.  # noqa: E501
        :type enabled: bool
        :param connected: The connected of this CacheHealthResponse.  # noqa: E501
        :type connected: bool
        :param status: The status of this CacheHealthResponse.  # noqa: E501
        :type status: str
        :param response_time_ms: The response_time_ms of this CacheHealthResponse.  # noqa: E501
        :type response_time_ms: float
        """
        self.openapi_types = {
            'enabled': bool,
            'connected': bool,
            'status': str,
            'response_time_ms': float
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'connected': 'connected',
            'status': 'status',
            'response_time_ms': 'response_time_ms'
        }

        self._enabled = enabled
        self._connected = connected
        self._status = status
        self._response_time_ms = response_time_ms

    @classmethod
    def from_dict(cls, dikt) -> 'CacheHealthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CacheHealthResponse of this CacheHealthResponse.  # noqa: E501
        :rtype: CacheHealthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this CacheHealthResponse.


        :return: The enabled of this CacheHealthResponse.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this CacheHealthResponse.


        :param enabled: The enabled of this CacheHealthResponse.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def connected(self) -> bool:
        """Gets the connected of this CacheHealthResponse.


        :return: The connected of this CacheHealthResponse.
        :rtype: bool
        """
        return self._connected

    @connected.setter
    def connected(self, connected: bool):
        """Sets the connected of this CacheHealthResponse.


        :param connected: The connected of this CacheHealthResponse.
        :type connected: bool
        """

        self._connected = connected

    @property
    def status(self) -> str:
        """Gets the status of this CacheHealthResponse.


        :return: The status of this CacheHealthResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this CacheHealthResponse.


        :param status: The status of this CacheHealthResponse.
        :type status: str
        """
        allowed_values = ["healthy", "unhealthy", "disabled"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def response_time_ms(self) -> float:
        """Gets the response_time_ms of this CacheHealthResponse.


        :return: The response_time_ms of this CacheHealthResponse.
        :rtype: float
        """
        return self._response_time_ms

    @response_time_ms.setter
    def response_time_ms(self, response_time_ms: float):
        """Sets the response_time_ms of this CacheHealthResponse.


        :param response_time_ms: The response_time_ms of this CacheHealthResponse.
        :type response_time_ms: float
        """

        self._response_time_ms = response_time_ms
