from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.preprocessed_images import PreprocessedImages
from ensemble_inference import util

from ensemble_inference.models.preprocessed_images import PreprocessedImages  # noqa: E501

class ClassifyImageRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, preprocessed_images=None):  # noqa: E501
        """ClassifyImageRequest - a model defined in OpenAPI

        :param preprocessed_images: The preprocessed_images of this ClassifyImageRequest.  # noqa: E501
        :type preprocessed_images: PreprocessedImages
        """
        self.openapi_types = {
            'preprocessed_images': PreprocessedImages
        }

        self.attribute_map = {
            'preprocessed_images': 'preprocessed_images'
        }

        self._preprocessed_images = preprocessed_images

    @classmethod
    def from_dict(cls, dikt) -> 'ClassifyImageRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The classifyImage_request of this ClassifyImageRequest.  # noqa: E501
        :rtype: ClassifyImageRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preprocessed_images(self) -> PreprocessedImages:
        """Gets the preprocessed_images of this ClassifyImageRequest.


        :return: The preprocessed_images of this ClassifyImageRequest.
        :rtype: PreprocessedImages
        """
        return self._preprocessed_images

    @preprocessed_images.setter
    def preprocessed_images(self, preprocessed_images: PreprocessedImages):
        """Sets the preprocessed_images of this ClassifyImageRequest.


        :param preprocessed_images: The preprocessed_images of this ClassifyImageRequest.
        :type preprocessed_images: PreprocessedImages
        """
        if preprocessed_images is None:
            raise ValueError("Invalid value for `preprocessed_images`, must not be `None`")  # noqa: E501

        self._preprocessed_images = preprocessed_images
