from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ClassProbability(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, label=None, probability=None):  # noqa: E501
        """ClassProbability - a model defined in OpenAPI

        :param id: The id of this ClassProbability.  # noqa: E501
        :type id: str
        :param label: The label of this ClassProbability.  # noqa: E501
        :type label: str
        :param probability: The probability of this ClassProbability.  # noqa: E501
        :type probability: float
        """
        self.openapi_types = {
            'id': str,
            'label': str,
            'probability': float
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'probability': 'probability'
        }

        self._id = id
        self._label = label
        self._probability = probability

    @classmethod
    def from_dict(cls, dikt) -> 'ClassProbability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClassProbability of this ClassProbability.  # noqa: E501
        :rtype: ClassProbability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ClassProbability.

        Class ID  # noqa: E501

        :return: The id of this ClassProbability.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ClassProbability.

        Class ID  # noqa: E501

        :param id: The id of this ClassProbability.
        :type id: str
        """
        allowed_values = ["DR_0", "DR_1", "DR_2", "DR_3", "DR_4"]  # noqa: E501
        if id not in allowed_values:
            raise ValueError(
                "Invalid value for `id` ({0}), must be one of {1}"
                .format(id, allowed_values)
            )

        self._id = id

    @property
    def label(self) -> str:
        """Gets the label of this ClassProbability.

        Full class label  # noqa: E501

        :return: The label of this ClassProbability.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this ClassProbability.

        Full class label  # noqa: E501

        :param label: The label of this ClassProbability.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def probability(self) -> float:
        """Gets the probability of this ClassProbability.


        :return: The probability of this ClassProbability.
        :rtype: float
        """
        return self._probability

    @probability.setter
    def probability(self, probability: float):
        """Sets the probability of this ClassProbability.


        :param probability: The probability of this ClassProbability.
        :type probability: float
        """
        if probability is None:
            raise ValueError("Invalid value for `probability`, must not be `None`")  # noqa: E501
        if probability is not None and probability > 1:  # noqa: E501
            raise ValueError("Invalid value for `probability`, must be a value less than or equal to `1`")  # noqa: E501
        if probability is not None and probability < 0:  # noqa: E501
            raise ValueError("Invalid value for `probability`, must be a value greater than or equal to `0`")  # noqa: E501

        self._probability = probability
