from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.operation_status import OperationStatus
from ensemble_inference.models.prediction_result import PredictionResult
from ensemble_inference import util

from ensemble_inference.models.operation_status import OperationStatus  # noqa: E501
from ensemble_inference.models.prediction_result import PredictionResult  # noqa: E501

class ClassifyResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, classification_time_seconds=None, prediction=None):  # noqa: E501
        """ClassifyResponse - a model defined in OpenAPI

        :param status: The status of this ClassifyResponse.  # noqa: E501
        :type status: OperationStatus
        :param classification_time_seconds: The classification_time_seconds of this ClassifyResponse.  # noqa: E501
        :type classification_time_seconds: float
        :param prediction: The prediction of this ClassifyResponse.  # noqa: E501
        :type prediction: PredictionResult
        """
        self.openapi_types = {
            'status': OperationStatus,
            'classification_time_seconds': float,
            'prediction': PredictionResult
        }

        self.attribute_map = {
            'status': 'status',
            'classification_time_seconds': 'classification_time_seconds',
            'prediction': 'prediction'
        }

        self._status = status
        self._classification_time_seconds = classification_time_seconds
        self._prediction = prediction

    @classmethod
    def from_dict(cls, dikt) -> 'ClassifyResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClassifyResponse of this ClassifyResponse.  # noqa: E501
        :rtype: ClassifyResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> OperationStatus:
        """Gets the status of this ClassifyResponse.


        :return: The status of this ClassifyResponse.
        :rtype: OperationStatus
        """
        return self._status

    @status.setter
    def status(self, status: OperationStatus):
        """Sets the status of this ClassifyResponse.


        :param status: The status of this ClassifyResponse.
        :type status: OperationStatus
        """

        self._status = status

    @property
    def classification_time_seconds(self) -> float:
        """Gets the classification_time_seconds of this ClassifyResponse.


        :return: The classification_time_seconds of this ClassifyResponse.
        :rtype: float
        """
        return self._classification_time_seconds

    @classification_time_seconds.setter
    def classification_time_seconds(self, classification_time_seconds: float):
        """Sets the classification_time_seconds of this ClassifyResponse.


        :param classification_time_seconds: The classification_time_seconds of this ClassifyResponse.
        :type classification_time_seconds: float
        """

        self._classification_time_seconds = classification_time_seconds

    @property
    def prediction(self) -> PredictionResult:
        """Gets the prediction of this ClassifyResponse.


        :return: The prediction of this ClassifyResponse.
        :rtype: PredictionResult
        """
        return self._prediction

    @prediction.setter
    def prediction(self, prediction: PredictionResult):
        """Sets the prediction of this ClassifyResponse.


        :param prediction: The prediction of this ClassifyResponse.
        :type prediction: PredictionResult
        """

        self._prediction = prediction
