from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ClassifyImageRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, variants=None):  # noqa: E501
        """ClassifyImageRequest - a model defined in OpenAPI

        :param variants: The variants of this ClassifyImageRequest.  # noqa: E501
        :type variants: Dict[str, str]
        """
        self.openapi_types = {
            'variants': Dict[str, str]
        }

        self.attribute_map = {
            'variants': 'variants'
        }

        self._variants = variants

    @classmethod
    def from_dict(cls, dikt) -> 'ClassifyImageRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The classifyImage_request of this ClassifyImageRequest.  # noqa: E501
        :rtype: ClassifyImageRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def variants(self) -> Dict[str, str]:
        """Gets the variants of this ClassifyImageRequest.

        Base64-encoded preprocessed image variants  # noqa: E501

        :return: The variants of this ClassifyImageRequest.
        :rtype: Dict[str, str]
        """
        return self._variants

    @variants.setter
    def variants(self, variants: Dict[str, str]):
        """Sets the variants of this ClassifyImageRequest.

        Base64-encoded preprocessed image variants  # noqa: E501

        :param variants: The variants of this ClassifyImageRequest.
        :type variants: Dict[str, str]
        """
        if variants is None:
            raise ValueError("Invalid value for `variants`, must not be `None`")  # noqa: E501

        self._variants = variants
