from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.batch_processing_metrics import BatchProcessingMetrics
from ensemble_inference.models.classification_result import ClassificationResult
from ensemble_inference.models.operation_status import OperationStatus
from ensemble_inference import util

from ensemble_inference.models.batch_processing_metrics import BatchProcessingMetrics  # noqa: E501
from ensemble_inference.models.classification_result import ClassificationResult  # noqa: E501
from ensemble_inference.models.operation_status import OperationStatus  # noqa: E501

class ClassifyResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, cached=None, classification_time_seconds=None, batch_processing_metrics=None, classification=None):  # noqa: E501
        """ClassifyResponse - a model defined in OpenAPI

        :param status: The status of this ClassifyResponse.  # noqa: E501
        :type status: OperationStatus
        :param cached: The cached of this ClassifyResponse.  # noqa: E501
        :type cached: bool
        :param classification_time_seconds: The classification_time_seconds of this ClassifyResponse.  # noqa: E501
        :type classification_time_seconds: float
        :param batch_processing_metrics: The batch_processing_metrics of this ClassifyResponse.  # noqa: E501
        :type batch_processing_metrics: BatchProcessingMetrics
        :param classification: The classification of this ClassifyResponse.  # noqa: E501
        :type classification: ClassificationResult
        """
        self.openapi_types = {
            'status': OperationStatus,
            'cached': bool,
            'classification_time_seconds': float,
            'batch_processing_metrics': BatchProcessingMetrics,
            'classification': ClassificationResult
        }

        self.attribute_map = {
            'status': 'status',
            'cached': 'cached',
            'classification_time_seconds': 'classification_time_seconds',
            'batch_processing_metrics': 'batch_processing_metrics',
            'classification': 'classification'
        }

        self._status = status
        self._cached = cached
        self._classification_time_seconds = classification_time_seconds
        self._batch_processing_metrics = batch_processing_metrics
        self._classification = classification

    @classmethod
    def from_dict(cls, dikt) -> 'ClassifyResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClassifyResponse of this ClassifyResponse.  # noqa: E501
        :rtype: ClassifyResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> OperationStatus:
        """Gets the status of this ClassifyResponse.


        :return: The status of this ClassifyResponse.
        :rtype: OperationStatus
        """
        return self._status

    @status.setter
    def status(self, status: OperationStatus):
        """Sets the status of this ClassifyResponse.


        :param status: The status of this ClassifyResponse.
        :type status: OperationStatus
        """

        self._status = status

    @property
    def cached(self) -> bool:
        """Gets the cached of this ClassifyResponse.

        Whether result was retrieved from cache  # noqa: E501

        :return: The cached of this ClassifyResponse.
        :rtype: bool
        """
        return self._cached

    @cached.setter
    def cached(self, cached: bool):
        """Sets the cached of this ClassifyResponse.

        Whether result was retrieved from cache  # noqa: E501

        :param cached: The cached of this ClassifyResponse.
        :type cached: bool
        """

        self._cached = cached

    @property
    def classification_time_seconds(self) -> float:
        """Gets the classification_time_seconds of this ClassifyResponse.


        :return: The classification_time_seconds of this ClassifyResponse.
        :rtype: float
        """
        return self._classification_time_seconds

    @classification_time_seconds.setter
    def classification_time_seconds(self, classification_time_seconds: float):
        """Sets the classification_time_seconds of this ClassifyResponse.


        :param classification_time_seconds: The classification_time_seconds of this ClassifyResponse.
        :type classification_time_seconds: float
        """

        self._classification_time_seconds = classification_time_seconds

    @property
    def batch_processing_metrics(self) -> BatchProcessingMetrics:
        """Gets the batch_processing_metrics of this ClassifyResponse.


        :return: The batch_processing_metrics of this ClassifyResponse.
        :rtype: BatchProcessingMetrics
        """
        return self._batch_processing_metrics

    @batch_processing_metrics.setter
    def batch_processing_metrics(self, batch_processing_metrics: BatchProcessingMetrics):
        """Sets the batch_processing_metrics of this ClassifyResponse.


        :param batch_processing_metrics: The batch_processing_metrics of this ClassifyResponse.
        :type batch_processing_metrics: BatchProcessingMetrics
        """

        self._batch_processing_metrics = batch_processing_metrics

    @property
    def classification(self) -> ClassificationResult:
        """Gets the classification of this ClassifyResponse.


        :return: The classification of this ClassifyResponse.
        :rtype: ClassificationResult
        """
        return self._classification

    @classification.setter
    def classification(self, classification: ClassificationResult):
        """Sets the classification of this ClassifyResponse.


        :param classification: The classification of this ClassifyResponse.
        :type classification: ClassificationResult
        """

        self._classification = classification
