from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ClearCacheRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pattern=None):  # noqa: E501
        """ClearCacheRequest - a model defined in OpenAPI

        :param pattern: The pattern of this ClearCacheRequest.  # noqa: E501
        :type pattern: str
        """
        self.openapi_types = {
            'pattern': str
        }

        self.attribute_map = {
            'pattern': 'pattern'
        }

        self._pattern = pattern

    @classmethod
    def from_dict(cls, dikt) -> 'ClearCacheRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The clearCache_request of this ClearCacheRequest.  # noqa: E501
        :rtype: ClearCacheRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pattern(self) -> str:
        """Gets the pattern of this ClearCacheRequest.

        Optional pattern to match keys for deletion  # noqa: E501

        :return: The pattern of this ClearCacheRequest.
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern: str):
        """Sets the pattern of this ClearCacheRequest.

        Optional pattern to match keys for deletion  # noqa: E501

        :param pattern: The pattern of this ClearCacheRequest.
        :type pattern: str
        """

        self._pattern = pattern
