from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.dynamic_batching_config import DynamicBatchingConfig
from ensemble_inference.models.voting_strategy_enum import VotingStrategyEnum
from ensemble_inference import util

from ensemble_inference.models.dynamic_batching_config import DynamicBatchingConfig  # noqa: E501
from ensemble_inference.models.voting_strategy_enum import VotingStrategyEnum  # noqa: E501

class ConfigResponseClassification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, voting_strategy=VotingStrategyEnum.SOFT, force_cpu=None, confidence_threshold=None, dynamic_batching=None):  # noqa: E501
        """ConfigResponseClassification - a model defined in OpenAPI

        :param voting_strategy: The voting_strategy of this ConfigResponseClassification.  # noqa: E501
        :type voting_strategy: VotingStrategyEnum
        :param force_cpu: The force_cpu of this ConfigResponseClassification.  # noqa: E501
        :type force_cpu: bool
        :param confidence_threshold: The confidence_threshold of this ConfigResponseClassification.  # noqa: E501
        :type confidence_threshold: float
        :param dynamic_batching: The dynamic_batching of this ConfigResponseClassification.  # noqa: E501
        :type dynamic_batching: DynamicBatchingConfig
        """
        self.openapi_types = {
            'voting_strategy': VotingStrategyEnum,
            'force_cpu': bool,
            'confidence_threshold': float,
            'dynamic_batching': DynamicBatchingConfig
        }

        self.attribute_map = {
            'voting_strategy': 'voting_strategy',
            'force_cpu': 'force_cpu',
            'confidence_threshold': 'confidence_threshold',
            'dynamic_batching': 'dynamic_batching'
        }

        self._voting_strategy = voting_strategy
        self._force_cpu = force_cpu
        self._confidence_threshold = confidence_threshold
        self._dynamic_batching = dynamic_batching

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigResponseClassification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigResponse_classification of this ConfigResponseClassification.  # noqa: E501
        :rtype: ConfigResponseClassification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voting_strategy(self) -> VotingStrategyEnum:
        """Gets the voting_strategy of this ConfigResponseClassification.


        :return: The voting_strategy of this ConfigResponseClassification.
        :rtype: VotingStrategyEnum
        """
        return self._voting_strategy

    @voting_strategy.setter
    def voting_strategy(self, voting_strategy: VotingStrategyEnum):
        """Sets the voting_strategy of this ConfigResponseClassification.


        :param voting_strategy: The voting_strategy of this ConfigResponseClassification.
        :type voting_strategy: VotingStrategyEnum
        """

        self._voting_strategy = voting_strategy

    @property
    def force_cpu(self) -> bool:
        """Gets the force_cpu of this ConfigResponseClassification.


        :return: The force_cpu of this ConfigResponseClassification.
        :rtype: bool
        """
        return self._force_cpu

    @force_cpu.setter
    def force_cpu(self, force_cpu: bool):
        """Sets the force_cpu of this ConfigResponseClassification.


        :param force_cpu: The force_cpu of this ConfigResponseClassification.
        :type force_cpu: bool
        """

        self._force_cpu = force_cpu

    @property
    def confidence_threshold(self) -> float:
        """Gets the confidence_threshold of this ConfigResponseClassification.


        :return: The confidence_threshold of this ConfigResponseClassification.
        :rtype: float
        """
        return self._confidence_threshold

    @confidence_threshold.setter
    def confidence_threshold(self, confidence_threshold: float):
        """Sets the confidence_threshold of this ConfigResponseClassification.


        :param confidence_threshold: The confidence_threshold of this ConfigResponseClassification.
        :type confidence_threshold: float
        """

        self._confidence_threshold = confidence_threshold

    @property
    def dynamic_batching(self) -> DynamicBatchingConfig:
        """Gets the dynamic_batching of this ConfigResponseClassification.


        :return: The dynamic_batching of this ConfigResponseClassification.
        :rtype: DynamicBatchingConfig
        """
        return self._dynamic_batching

    @dynamic_batching.setter
    def dynamic_batching(self, dynamic_batching: DynamicBatchingConfig):
        """Sets the dynamic_batching of this ConfigResponseClassification.


        :param dynamic_batching: The dynamic_batching of this ConfigResponseClassification.
        :type dynamic_batching: DynamicBatchingConfig
        """

        self._dynamic_batching = dynamic_batching
