from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ConfigResponsePreprocessing(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, target_resolution=None, normalize_pixels=None, black_border_clipping=None, parallel_processing=None):  # noqa: E501
        """ConfigResponsePreprocessing - a model defined in OpenAPI

        :param target_resolution: The target_resolution of this ConfigResponsePreprocessing.  # noqa: E501
        :type target_resolution: List[int]
        :param normalize_pixels: The normalize_pixels of this ConfigResponsePreprocessing.  # noqa: E501
        :type normalize_pixels: bool
        :param black_border_clipping: The black_border_clipping of this ConfigResponsePreprocessing.  # noqa: E501
        :type black_border_clipping: bool
        :param parallel_processing: The parallel_processing of this ConfigResponsePreprocessing.  # noqa: E501
        :type parallel_processing: bool
        """
        self.openapi_types = {
            'target_resolution': List[int],
            'normalize_pixels': bool,
            'black_border_clipping': bool,
            'parallel_processing': bool
        }

        self.attribute_map = {
            'target_resolution': 'target_resolution',
            'normalize_pixels': 'normalize_pixels',
            'black_border_clipping': 'black_border_clipping',
            'parallel_processing': 'parallel_processing'
        }

        self._target_resolution = target_resolution
        self._normalize_pixels = normalize_pixels
        self._black_border_clipping = black_border_clipping
        self._parallel_processing = parallel_processing

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigResponsePreprocessing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigResponse_preprocessing of this ConfigResponsePreprocessing.  # noqa: E501
        :rtype: ConfigResponsePreprocessing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_resolution(self) -> List[int]:
        """Gets the target_resolution of this ConfigResponsePreprocessing.


        :return: The target_resolution of this ConfigResponsePreprocessing.
        :rtype: List[int]
        """
        return self._target_resolution

    @target_resolution.setter
    def target_resolution(self, target_resolution: List[int]):
        """Sets the target_resolution of this ConfigResponsePreprocessing.


        :param target_resolution: The target_resolution of this ConfigResponsePreprocessing.
        :type target_resolution: List[int]
        """

        self._target_resolution = target_resolution

    @property
    def normalize_pixels(self) -> bool:
        """Gets the normalize_pixels of this ConfigResponsePreprocessing.


        :return: The normalize_pixels of this ConfigResponsePreprocessing.
        :rtype: bool
        """
        return self._normalize_pixels

    @normalize_pixels.setter
    def normalize_pixels(self, normalize_pixels: bool):
        """Sets the normalize_pixels of this ConfigResponsePreprocessing.


        :param normalize_pixels: The normalize_pixels of this ConfigResponsePreprocessing.
        :type normalize_pixels: bool
        """

        self._normalize_pixels = normalize_pixels

    @property
    def black_border_clipping(self) -> bool:
        """Gets the black_border_clipping of this ConfigResponsePreprocessing.


        :return: The black_border_clipping of this ConfigResponsePreprocessing.
        :rtype: bool
        """
        return self._black_border_clipping

    @black_border_clipping.setter
    def black_border_clipping(self, black_border_clipping: bool):
        """Sets the black_border_clipping of this ConfigResponsePreprocessing.


        :param black_border_clipping: The black_border_clipping of this ConfigResponsePreprocessing.
        :type black_border_clipping: bool
        """

        self._black_border_clipping = black_border_clipping

    @property
    def parallel_processing(self) -> bool:
        """Gets the parallel_processing of this ConfigResponsePreprocessing.


        :return: The parallel_processing of this ConfigResponsePreprocessing.
        :rtype: bool
        """
        return self._parallel_processing

    @parallel_processing.setter
    def parallel_processing(self, parallel_processing: bool):
        """Sets the parallel_processing of this ConfigResponsePreprocessing.


        :param parallel_processing: The parallel_processing of this ConfigResponsePreprocessing.
        :type parallel_processing: bool
        """

        self._parallel_processing = parallel_processing
