from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.config_response_classification import ConfigResponseClassification
from ensemble_inference.models.config_response_preprocessing import ConfigResponsePreprocessing
from ensemble_inference import util

from ensemble_inference.models.config_response_classification import ConfigResponseClassification  # noqa: E501
from ensemble_inference.models.config_response_preprocessing import ConfigResponsePreprocessing  # noqa: E501

class ConfigResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, preprocessing=None, classification=None):  # noqa: E501
        """ConfigResponse - a model defined in OpenAPI

        :param preprocessing: The preprocessing of this ConfigResponse.  # noqa: E501
        :type preprocessing: ConfigResponsePreprocessing
        :param classification: The classification of this ConfigResponse.  # noqa: E501
        :type classification: ConfigResponseClassification
        """
        self.openapi_types = {
            'preprocessing': ConfigResponsePreprocessing,
            'classification': ConfigResponseClassification
        }

        self.attribute_map = {
            'preprocessing': 'preprocessing',
            'classification': 'classification'
        }

        self._preprocessing = preprocessing
        self._classification = classification

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigResponse of this ConfigResponse.  # noqa: E501
        :rtype: ConfigResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preprocessing(self) -> ConfigResponsePreprocessing:
        """Gets the preprocessing of this ConfigResponse.


        :return: The preprocessing of this ConfigResponse.
        :rtype: ConfigResponsePreprocessing
        """
        return self._preprocessing

    @preprocessing.setter
    def preprocessing(self, preprocessing: ConfigResponsePreprocessing):
        """Sets the preprocessing of this ConfigResponse.


        :param preprocessing: The preprocessing of this ConfigResponse.
        :type preprocessing: ConfigResponsePreprocessing
        """

        self._preprocessing = preprocessing

    @property
    def classification(self) -> ConfigResponseClassification:
        """Gets the classification of this ConfigResponse.


        :return: The classification of this ConfigResponse.
        :rtype: ConfigResponseClassification
        """
        return self._classification

    @classification.setter
    def classification(self, classification: ConfigResponseClassification):
        """Sets the classification of this ConfigResponse.


        :param classification: The classification of this ConfigResponse.
        :type classification: ConfigResponseClassification
        """

        self._classification = classification
