from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ConfigResponseClassification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, voting_strategy=None, force_cpu=None, confidence_threshold=None):  # noqa: E501
        """ConfigResponseClassification - a model defined in OpenAPI

        :param voting_strategy: The voting_strategy of this ConfigResponseClassification.  # noqa: E501
        :type voting_strategy: str
        :param force_cpu: The force_cpu of this ConfigResponseClassification.  # noqa: E501
        :type force_cpu: bool
        :param confidence_threshold: The confidence_threshold of this ConfigResponseClassification.  # noqa: E501
        :type confidence_threshold: float
        """
        self.openapi_types = {
            'voting_strategy': str,
            'force_cpu': bool,
            'confidence_threshold': float
        }

        self.attribute_map = {
            'voting_strategy': 'voting_strategy',
            'force_cpu': 'force_cpu',
            'confidence_threshold': 'confidence_threshold'
        }

        self._voting_strategy = voting_strategy
        self._force_cpu = force_cpu
        self._confidence_threshold = confidence_threshold

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigResponseClassification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigResponse_classification of this ConfigResponseClassification.  # noqa: E501
        :rtype: ConfigResponseClassification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voting_strategy(self) -> str:
        """Gets the voting_strategy of this ConfigResponseClassification.


        :return: The voting_strategy of this ConfigResponseClassification.
        :rtype: str
        """
        return self._voting_strategy

    @voting_strategy.setter
    def voting_strategy(self, voting_strategy: str):
        """Sets the voting_strategy of this ConfigResponseClassification.


        :param voting_strategy: The voting_strategy of this ConfigResponseClassification.
        :type voting_strategy: str
        """
        allowed_values = ["soft", "hard"]  # noqa: E501
        if voting_strategy not in allowed_values:
            raise ValueError(
                "Invalid value for `voting_strategy` ({0}), must be one of {1}"
                .format(voting_strategy, allowed_values)
            )

        self._voting_strategy = voting_strategy

    @property
    def force_cpu(self) -> bool:
        """Gets the force_cpu of this ConfigResponseClassification.


        :return: The force_cpu of this ConfigResponseClassification.
        :rtype: bool
        """
        return self._force_cpu

    @force_cpu.setter
    def force_cpu(self, force_cpu: bool):
        """Sets the force_cpu of this ConfigResponseClassification.


        :param force_cpu: The force_cpu of this ConfigResponseClassification.
        :type force_cpu: bool
        """

        self._force_cpu = force_cpu

    @property
    def confidence_threshold(self) -> float:
        """Gets the confidence_threshold of this ConfigResponseClassification.


        :return: The confidence_threshold of this ConfigResponseClassification.
        :rtype: float
        """
        return self._confidence_threshold

    @confidence_threshold.setter
    def confidence_threshold(self, confidence_threshold: float):
        """Sets the confidence_threshold of this ConfigResponseClassification.


        :param confidence_threshold: The confidence_threshold of this ConfigResponseClassification.
        :type confidence_threshold: float
        """

        self._confidence_threshold = confidence_threshold
