from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class HealthResponseModules(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, preprocessor=None, classifier=None):  # noqa: E501
        """HealthResponseModules - a model defined in OpenAPI

        :param preprocessor: The preprocessor of this HealthResponseModules.  # noqa: E501
        :type preprocessor: bool
        :param classifier: The classifier of this HealthResponseModules.  # noqa: E501
        :type classifier: bool
        """
        self.openapi_types = {
            'preprocessor': bool,
            'classifier': bool
        }

        self.attribute_map = {
            'preprocessor': 'preprocessor',
            'classifier': 'classifier'
        }

        self._preprocessor = preprocessor
        self._classifier = classifier

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponseModules':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse_modules of this HealthResponseModules.  # noqa: E501
        :rtype: HealthResponseModules
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preprocessor(self) -> bool:
        """Gets the preprocessor of this HealthResponseModules.


        :return: The preprocessor of this HealthResponseModules.
        :rtype: bool
        """
        return self._preprocessor

    @preprocessor.setter
    def preprocessor(self, preprocessor: bool):
        """Sets the preprocessor of this HealthResponseModules.


        :param preprocessor: The preprocessor of this HealthResponseModules.
        :type preprocessor: bool
        """

        self._preprocessor = preprocessor

    @property
    def classifier(self) -> bool:
        """Gets the classifier of this HealthResponseModules.


        :return: The classifier of this HealthResponseModules.
        :rtype: bool
        """
        return self._classifier

    @classifier.setter
    def classifier(self, classifier: bool):
        """Sets the classifier of this HealthResponseModules.


        :param classifier: The classifier of this HealthResponseModules.
        :type classifier: bool
        """

        self._classifier = classifier
