from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.health_response_modules import HealthResponseModules
from ensemble_inference import util

from ensemble_inference.models.health_response_modules import HealthResponseModules  # noqa: E501

class HealthResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, timestamp=None, uptime=None, modules=None):  # noqa: E501
        """HealthResponse - a model defined in OpenAPI

        :param status: The status of this HealthResponse.  # noqa: E501
        :type status: str
        :param timestamp: The timestamp of this HealthResponse.  # noqa: E501
        :type timestamp: float
        :param uptime: The uptime of this HealthResponse.  # noqa: E501
        :type uptime: float
        :param modules: The modules of this HealthResponse.  # noqa: E501
        :type modules: HealthResponseModules
        """
        self.openapi_types = {
            'status': str,
            'timestamp': float,
            'uptime': float,
            'modules': HealthResponseModules
        }

        self.attribute_map = {
            'status': 'status',
            'timestamp': 'timestamp',
            'uptime': 'uptime',
            'modules': 'modules'
        }

        self._status = status
        self._timestamp = timestamp
        self._uptime = uptime
        self._modules = modules

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse of this HealthResponse.  # noqa: E501
        :rtype: HealthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this HealthResponse.


        :return: The status of this HealthResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this HealthResponse.


        :param status: The status of this HealthResponse.
        :type status: str
        """

        self._status = status

    @property
    def timestamp(self) -> float:
        """Gets the timestamp of this HealthResponse.


        :return: The timestamp of this HealthResponse.
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: float):
        """Sets the timestamp of this HealthResponse.


        :param timestamp: The timestamp of this HealthResponse.
        :type timestamp: float
        """

        self._timestamp = timestamp

    @property
    def uptime(self) -> float:
        """Gets the uptime of this HealthResponse.

        Server uptime in seconds  # noqa: E501

        :return: The uptime of this HealthResponse.
        :rtype: float
        """
        return self._uptime

    @uptime.setter
    def uptime(self, uptime: float):
        """Sets the uptime of this HealthResponse.

        Server uptime in seconds  # noqa: E501

        :param uptime: The uptime of this HealthResponse.
        :type uptime: float
        """

        self._uptime = uptime

    @property
    def modules(self) -> HealthResponseModules:
        """Gets the modules of this HealthResponse.


        :return: The modules of this HealthResponse.
        :rtype: HealthResponseModules
        """
        return self._modules

    @modules.setter
    def modules(self, modules: HealthResponseModules):
        """Sets the modules of this HealthResponse.


        :param modules: The modules of this HealthResponse.
        :type modules: HealthResponseModules
        """

        self._modules = modules
