from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ImageProperties(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, original_width_px=None, original_height_px=None, processed_width_px=None, processed_height_px=None):  # noqa: E501
        """ImageProperties - a model defined in OpenAPI

        :param original_width_px: The original_width_px of this ImageProperties.  # noqa: E501
        :type original_width_px: int
        :param original_height_px: The original_height_px of this ImageProperties.  # noqa: E501
        :type original_height_px: int
        :param processed_width_px: The processed_width_px of this ImageProperties.  # noqa: E501
        :type processed_width_px: int
        :param processed_height_px: The processed_height_px of this ImageProperties.  # noqa: E501
        :type processed_height_px: int
        """
        self.openapi_types = {
            'original_width_px': int,
            'original_height_px': int,
            'processed_width_px': int,
            'processed_height_px': int
        }

        self.attribute_map = {
            'original_width_px': 'original_width_px',
            'original_height_px': 'original_height_px',
            'processed_width_px': 'processed_width_px',
            'processed_height_px': 'processed_height_px'
        }

        self._original_width_px = original_width_px
        self._original_height_px = original_height_px
        self._processed_width_px = processed_width_px
        self._processed_height_px = processed_height_px

    @classmethod
    def from_dict(cls, dikt) -> 'ImageProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageProperties of this ImageProperties.  # noqa: E501
        :rtype: ImageProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def original_width_px(self) -> int:
        """Gets the original_width_px of this ImageProperties.


        :return: The original_width_px of this ImageProperties.
        :rtype: int
        """
        return self._original_width_px

    @original_width_px.setter
    def original_width_px(self, original_width_px: int):
        """Sets the original_width_px of this ImageProperties.


        :param original_width_px: The original_width_px of this ImageProperties.
        :type original_width_px: int
        """
        if original_width_px is None:
            raise ValueError("Invalid value for `original_width_px`, must not be `None`")  # noqa: E501

        self._original_width_px = original_width_px

    @property
    def original_height_px(self) -> int:
        """Gets the original_height_px of this ImageProperties.


        :return: The original_height_px of this ImageProperties.
        :rtype: int
        """
        return self._original_height_px

    @original_height_px.setter
    def original_height_px(self, original_height_px: int):
        """Sets the original_height_px of this ImageProperties.


        :param original_height_px: The original_height_px of this ImageProperties.
        :type original_height_px: int
        """
        if original_height_px is None:
            raise ValueError("Invalid value for `original_height_px`, must not be `None`")  # noqa: E501

        self._original_height_px = original_height_px

    @property
    def processed_width_px(self) -> int:
        """Gets the processed_width_px of this ImageProperties.


        :return: The processed_width_px of this ImageProperties.
        :rtype: int
        """
        return self._processed_width_px

    @processed_width_px.setter
    def processed_width_px(self, processed_width_px: int):
        """Sets the processed_width_px of this ImageProperties.


        :param processed_width_px: The processed_width_px of this ImageProperties.
        :type processed_width_px: int
        """
        if processed_width_px is None:
            raise ValueError("Invalid value for `processed_width_px`, must not be `None`")  # noqa: E501

        self._processed_width_px = processed_width_px

    @property
    def processed_height_px(self) -> int:
        """Gets the processed_height_px of this ImageProperties.


        :return: The processed_height_px of this ImageProperties.
        :rtype: int
        """
        return self._processed_height_px

    @processed_height_px.setter
    def processed_height_px(self, processed_height_px: int):
        """Sets the processed_height_px of this ImageProperties.


        :param processed_height_px: The processed_height_px of this ImageProperties.
        :type processed_height_px: int
        """
        if processed_height_px is None:
            raise ValueError("Invalid value for `processed_height_px`, must not be `None`")  # noqa: E501

        self._processed_height_px = processed_height_px
