from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.info_response_modules_classification import InfoResponseModulesClassification
from ensemble_inference.models.info_response_modules_preprocessing import InfoResponseModulesPreprocessing
from ensemble_inference import util

from ensemble_inference.models.info_response_modules_classification import InfoResponseModulesClassification  # noqa: E501
from ensemble_inference.models.info_response_modules_preprocessing import InfoResponseModulesPreprocessing  # noqa: E501

class InfoResponseModules(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, preprocessing=None, classification=None):  # noqa: E501
        """InfoResponseModules - a model defined in OpenAPI

        :param preprocessing: The preprocessing of this InfoResponseModules.  # noqa: E501
        :type preprocessing: InfoResponseModulesPreprocessing
        :param classification: The classification of this InfoResponseModules.  # noqa: E501
        :type classification: InfoResponseModulesClassification
        """
        self.openapi_types = {
            'preprocessing': InfoResponseModulesPreprocessing,
            'classification': InfoResponseModulesClassification
        }

        self.attribute_map = {
            'preprocessing': 'preprocessing',
            'classification': 'classification'
        }

        self._preprocessing = preprocessing
        self._classification = classification

    @classmethod
    def from_dict(cls, dikt) -> 'InfoResponseModules':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InfoResponse_modules of this InfoResponseModules.  # noqa: E501
        :rtype: InfoResponseModules
        """
        return util.deserialize_model(dikt, cls)

    @property
    def preprocessing(self) -> InfoResponseModulesPreprocessing:
        """Gets the preprocessing of this InfoResponseModules.


        :return: The preprocessing of this InfoResponseModules.
        :rtype: InfoResponseModulesPreprocessing
        """
        return self._preprocessing

    @preprocessing.setter
    def preprocessing(self, preprocessing: InfoResponseModulesPreprocessing):
        """Sets the preprocessing of this InfoResponseModules.


        :param preprocessing: The preprocessing of this InfoResponseModules.
        :type preprocessing: InfoResponseModulesPreprocessing
        """

        self._preprocessing = preprocessing

    @property
    def classification(self) -> InfoResponseModulesClassification:
        """Gets the classification of this InfoResponseModules.


        :return: The classification of this InfoResponseModules.
        :rtype: InfoResponseModulesClassification
        """
        return self._classification

    @classification.setter
    def classification(self, classification: InfoResponseModulesClassification):
        """Sets the classification of this InfoResponseModules.


        :param classification: The classification of this InfoResponseModules.
        :type classification: InfoResponseModulesClassification
        """

        self._classification = classification
