from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.dynamic_batching_config import DynamicBatchingConfig
from ensemble_inference.models.voting_strategy_enum import VotingStrategyEnum
from ensemble_inference import util

from ensemble_inference.models.dynamic_batching_config import DynamicBatchingConfig  # noqa: E501
from ensemble_inference.models.voting_strategy_enum import VotingStrategyEnum  # noqa: E501

class InfoResponseModulesClassification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=None, models=None, voting_strategy=VotingStrategyEnum.SOFT, dynamic_batching=None):  # noqa: E501
        """InfoResponseModulesClassification - a model defined in OpenAPI

        :param enabled: The enabled of this InfoResponseModulesClassification.  # noqa: E501
        :type enabled: bool
        :param models: The models of this InfoResponseModulesClassification.  # noqa: E501
        :type models: int
        :param voting_strategy: The voting_strategy of this InfoResponseModulesClassification.  # noqa: E501
        :type voting_strategy: VotingStrategyEnum
        :param dynamic_batching: The dynamic_batching of this InfoResponseModulesClassification.  # noqa: E501
        :type dynamic_batching: DynamicBatchingConfig
        """
        self.openapi_types = {
            'enabled': bool,
            'models': int,
            'voting_strategy': VotingStrategyEnum,
            'dynamic_batching': DynamicBatchingConfig
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'models': 'models',
            'voting_strategy': 'voting_strategy',
            'dynamic_batching': 'dynamic_batching'
        }

        self._enabled = enabled
        self._models = models
        self._voting_strategy = voting_strategy
        self._dynamic_batching = dynamic_batching

    @classmethod
    def from_dict(cls, dikt) -> 'InfoResponseModulesClassification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InfoResponse_modules_classification of this InfoResponseModulesClassification.  # noqa: E501
        :rtype: InfoResponseModulesClassification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this InfoResponseModulesClassification.


        :return: The enabled of this InfoResponseModulesClassification.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this InfoResponseModulesClassification.


        :param enabled: The enabled of this InfoResponseModulesClassification.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def models(self) -> int:
        """Gets the models of this InfoResponseModulesClassification.


        :return: The models of this InfoResponseModulesClassification.
        :rtype: int
        """
        return self._models

    @models.setter
    def models(self, models: int):
        """Sets the models of this InfoResponseModulesClassification.


        :param models: The models of this InfoResponseModulesClassification.
        :type models: int
        """

        self._models = models

    @property
    def voting_strategy(self) -> VotingStrategyEnum:
        """Gets the voting_strategy of this InfoResponseModulesClassification.


        :return: The voting_strategy of this InfoResponseModulesClassification.
        :rtype: VotingStrategyEnum
        """
        return self._voting_strategy

    @voting_strategy.setter
    def voting_strategy(self, voting_strategy: VotingStrategyEnum):
        """Sets the voting_strategy of this InfoResponseModulesClassification.


        :param voting_strategy: The voting_strategy of this InfoResponseModulesClassification.
        :type voting_strategy: VotingStrategyEnum
        """

        self._voting_strategy = voting_strategy

    @property
    def dynamic_batching(self) -> DynamicBatchingConfig:
        """Gets the dynamic_batching of this InfoResponseModulesClassification.


        :return: The dynamic_batching of this InfoResponseModulesClassification.
        :rtype: DynamicBatchingConfig
        """
        return self._dynamic_batching

    @dynamic_batching.setter
    def dynamic_batching(self, dynamic_batching: DynamicBatchingConfig):
        """Sets the dynamic_batching of this InfoResponseModulesClassification.


        :param dynamic_batching: The dynamic_batching of this InfoResponseModulesClassification.
        :type dynamic_batching: DynamicBatchingConfig
        """

        self._dynamic_batching = dynamic_batching
