from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class InfoResponseModulesPreprocessing(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=None, variants=None, clipping_methods=None):  # noqa: E501
        """InfoResponseModulesPreprocessing - a model defined in OpenAPI

        :param enabled: The enabled of this InfoResponseModulesPreprocessing.  # noqa: E501
        :type enabled: bool
        :param variants: The variants of this InfoResponseModulesPreprocessing.  # noqa: E501
        :type variants: int
        :param clipping_methods: The clipping_methods of this InfoResponseModulesPreprocessing.  # noqa: E501
        :type clipping_methods: int
        """
        self.openapi_types = {
            'enabled': bool,
            'variants': int,
            'clipping_methods': int
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'variants': 'variants',
            'clipping_methods': 'clipping_methods'
        }

        self._enabled = enabled
        self._variants = variants
        self._clipping_methods = clipping_methods

    @classmethod
    def from_dict(cls, dikt) -> 'InfoResponseModulesPreprocessing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InfoResponse_modules_preprocessing of this InfoResponseModulesPreprocessing.  # noqa: E501
        :rtype: InfoResponseModulesPreprocessing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this InfoResponseModulesPreprocessing.


        :return: The enabled of this InfoResponseModulesPreprocessing.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this InfoResponseModulesPreprocessing.


        :param enabled: The enabled of this InfoResponseModulesPreprocessing.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def variants(self) -> int:
        """Gets the variants of this InfoResponseModulesPreprocessing.


        :return: The variants of this InfoResponseModulesPreprocessing.
        :rtype: int
        """
        return self._variants

    @variants.setter
    def variants(self, variants: int):
        """Sets the variants of this InfoResponseModulesPreprocessing.


        :param variants: The variants of this InfoResponseModulesPreprocessing.
        :type variants: int
        """

        self._variants = variants

    @property
    def clipping_methods(self) -> int:
        """Gets the clipping_methods of this InfoResponseModulesPreprocessing.


        :return: The clipping_methods of this InfoResponseModulesPreprocessing.
        :rtype: int
        """
        return self._clipping_methods

    @clipping_methods.setter
    def clipping_methods(self, clipping_methods: int):
        """Sets the clipping_methods of this InfoResponseModulesPreprocessing.


        :param clipping_methods: The clipping_methods of this InfoResponseModulesPreprocessing.
        :type clipping_methods: int
        """

        self._clipping_methods = clipping_methods
