from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.info_response_modules import InfoResponseModules
from ensemble_inference import util

from ensemble_inference.models.info_response_modules import InfoResponseModules  # noqa: E501

class InfoResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, version=None, modules=None, endpoints=None, paper_reference=None):  # noqa: E501
        """InfoResponse - a model defined in OpenAPI

        :param name: The name of this InfoResponse.  # noqa: E501
        :type name: str
        :param version: The version of this InfoResponse.  # noqa: E501
        :type version: str
        :param modules: The modules of this InfoResponse.  # noqa: E501
        :type modules: InfoResponseModules
        :param endpoints: The endpoints of this InfoResponse.  # noqa: E501
        :type endpoints: Dict[str, str]
        :param paper_reference: The paper_reference of this InfoResponse.  # noqa: E501
        :type paper_reference: str
        """
        self.openapi_types = {
            'name': str,
            'version': str,
            'modules': InfoResponseModules,
            'endpoints': Dict[str, str],
            'paper_reference': str
        }

        self.attribute_map = {
            'name': 'name',
            'version': 'version',
            'modules': 'modules',
            'endpoints': 'endpoints',
            'paper_reference': 'paper_reference'
        }

        self._name = name
        self._version = version
        self._modules = modules
        self._endpoints = endpoints
        self._paper_reference = paper_reference

    @classmethod
    def from_dict(cls, dikt) -> 'InfoResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InfoResponse of this InfoResponse.  # noqa: E501
        :rtype: InfoResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InfoResponse.


        :return: The name of this InfoResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InfoResponse.


        :param name: The name of this InfoResponse.
        :type name: str
        """

        self._name = name

    @property
    def version(self) -> str:
        """Gets the version of this InfoResponse.


        :return: The version of this InfoResponse.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this InfoResponse.


        :param version: The version of this InfoResponse.
        :type version: str
        """

        self._version = version

    @property
    def modules(self) -> InfoResponseModules:
        """Gets the modules of this InfoResponse.


        :return: The modules of this InfoResponse.
        :rtype: InfoResponseModules
        """
        return self._modules

    @modules.setter
    def modules(self, modules: InfoResponseModules):
        """Sets the modules of this InfoResponse.


        :param modules: The modules of this InfoResponse.
        :type modules: InfoResponseModules
        """

        self._modules = modules

    @property
    def endpoints(self) -> Dict[str, str]:
        """Gets the endpoints of this InfoResponse.


        :return: The endpoints of this InfoResponse.
        :rtype: Dict[str, str]
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints: Dict[str, str]):
        """Sets the endpoints of this InfoResponse.


        :param endpoints: The endpoints of this InfoResponse.
        :type endpoints: Dict[str, str]
        """

        self._endpoints = endpoints

    @property
    def paper_reference(self) -> str:
        """Gets the paper_reference of this InfoResponse.


        :return: The paper_reference of this InfoResponse.
        :rtype: str
        """
        return self._paper_reference

    @paper_reference.setter
    def paper_reference(self, paper_reference: str):
        """Sets the paper_reference of this InfoResponse.


        :param paper_reference: The paper_reference of this InfoResponse.
        :type paper_reference: str
        """

        self._paper_reference = paper_reference
