from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class InfoResponseModulesExplainability(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=None, method=None, framework=None):  # noqa: E501
        """InfoResponseModulesExplainability - a model defined in OpenAPI

        :param enabled: The enabled of this InfoResponseModulesExplainability.  # noqa: E501
        :type enabled: bool
        :param method: The method of this InfoResponseModulesExplainability.  # noqa: E501
        :type method: str
        :param framework: The framework of this InfoResponseModulesExplainability.  # noqa: E501
        :type framework: str
        """
        self.openapi_types = {
            'enabled': bool,
            'method': str,
            'framework': str
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'method': 'method',
            'framework': 'framework'
        }

        self._enabled = enabled
        self._method = method
        self._framework = framework

    @classmethod
    def from_dict(cls, dikt) -> 'InfoResponseModulesExplainability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InfoResponse_modules_explainability of this InfoResponseModulesExplainability.  # noqa: E501
        :rtype: InfoResponseModulesExplainability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this InfoResponseModulesExplainability.

        True when explain=true requests are accepted  # noqa: E501

        :return: The enabled of this InfoResponseModulesExplainability.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this InfoResponseModulesExplainability.

        True when explain=true requests are accepted  # noqa: E501

        :param enabled: The enabled of this InfoResponseModulesExplainability.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def method(self) -> str:
        """Gets the method of this InfoResponseModulesExplainability.


        :return: The method of this InfoResponseModulesExplainability.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this InfoResponseModulesExplainability.


        :param method: The method of this InfoResponseModulesExplainability.
        :type method: str
        """

        self._method = method

    @property
    def framework(self) -> str:
        """Gets the framework of this InfoResponseModulesExplainability.


        :return: The framework of this InfoResponseModulesExplainability.
        :rtype: str
        """
        return self._framework

    @framework.setter
    def framework(self, framework: str):
        """Sets the framework of this InfoResponseModulesExplainability.


        :param framework: The framework of this InfoResponseModulesExplainability.
        :type framework: str
        """

        self._framework = framework
