from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ModelConfiguration(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, model_architecture=None, ensemble_size=None, trained_datasets=None, voting_strategy=None):  # noqa: E501
        """ModelConfiguration - a model defined in OpenAPI

        :param model_architecture: The model_architecture of this ModelConfiguration.  # noqa: E501
        :type model_architecture: str
        :param ensemble_size: The ensemble_size of this ModelConfiguration.  # noqa: E501
        :type ensemble_size: int
        :param trained_datasets: The trained_datasets of this ModelConfiguration.  # noqa: E501
        :type trained_datasets: List[str]
        :param voting_strategy: The voting_strategy of this ModelConfiguration.  # noqa: E501
        :type voting_strategy: str
        """
        self.openapi_types = {
            'model_architecture': str,
            'ensemble_size': int,
            'trained_datasets': List[str],
            'voting_strategy': str
        }

        self.attribute_map = {
            'model_architecture': 'model_architecture',
            'ensemble_size': 'ensemble_size',
            'trained_datasets': 'trained_datasets',
            'voting_strategy': 'voting_strategy'
        }

        self._model_architecture = model_architecture
        self._ensemble_size = ensemble_size
        self._trained_datasets = trained_datasets
        self._voting_strategy = voting_strategy

    @classmethod
    def from_dict(cls, dikt) -> 'ModelConfiguration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelConfiguration of this ModelConfiguration.  # noqa: E501
        :rtype: ModelConfiguration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_architecture(self) -> str:
        """Gets the model_architecture of this ModelConfiguration.


        :return: The model_architecture of this ModelConfiguration.
        :rtype: str
        """
        return self._model_architecture

    @model_architecture.setter
    def model_architecture(self, model_architecture: str):
        """Sets the model_architecture of this ModelConfiguration.


        :param model_architecture: The model_architecture of this ModelConfiguration.
        :type model_architecture: str
        """
        if model_architecture is None:
            raise ValueError("Invalid value for `model_architecture`, must not be `None`")  # noqa: E501

        self._model_architecture = model_architecture

    @property
    def ensemble_size(self) -> int:
        """Gets the ensemble_size of this ModelConfiguration.


        :return: The ensemble_size of this ModelConfiguration.
        :rtype: int
        """
        return self._ensemble_size

    @ensemble_size.setter
    def ensemble_size(self, ensemble_size: int):
        """Sets the ensemble_size of this ModelConfiguration.


        :param ensemble_size: The ensemble_size of this ModelConfiguration.
        :type ensemble_size: int
        """
        if ensemble_size is None:
            raise ValueError("Invalid value for `ensemble_size`, must not be `None`")  # noqa: E501

        self._ensemble_size = ensemble_size

    @property
    def trained_datasets(self) -> List[str]:
        """Gets the trained_datasets of this ModelConfiguration.


        :return: The trained_datasets of this ModelConfiguration.
        :rtype: List[str]
        """
        return self._trained_datasets

    @trained_datasets.setter
    def trained_datasets(self, trained_datasets: List[str]):
        """Sets the trained_datasets of this ModelConfiguration.


        :param trained_datasets: The trained_datasets of this ModelConfiguration.
        :type trained_datasets: List[str]
        """
        if trained_datasets is None:
            raise ValueError("Invalid value for `trained_datasets`, must not be `None`")  # noqa: E501

        self._trained_datasets = trained_datasets

    @property
    def voting_strategy(self) -> str:
        """Gets the voting_strategy of this ModelConfiguration.


        :return: The voting_strategy of this ModelConfiguration.
        :rtype: str
        """
        return self._voting_strategy

    @voting_strategy.setter
    def voting_strategy(self, voting_strategy: str):
        """Sets the voting_strategy of this ModelConfiguration.


        :param voting_strategy: The voting_strategy of this ModelConfiguration.
        :type voting_strategy: str
        """
        if voting_strategy is None:
            raise ValueError("Invalid value for `voting_strategy`, must not be `None`")  # noqa: E501

        self._voting_strategy = voting_strategy
