from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ModelExplanation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, model_architecture=None, preprocessing_variant=None, target_layer=None, heatmap_overlay=None, heatmap=None):  # noqa: E501
        """ModelExplanation - a model defined in OpenAPI

        :param model_architecture: The model_architecture of this ModelExplanation.  # noqa: E501
        :type model_architecture: str
        :param preprocessing_variant: The preprocessing_variant of this ModelExplanation.  # noqa: E501
        :type preprocessing_variant: str
        :param target_layer: The target_layer of this ModelExplanation.  # noqa: E501
        :type target_layer: str
        :param heatmap_overlay: The heatmap_overlay of this ModelExplanation.  # noqa: E501
        :type heatmap_overlay: str
        :param heatmap: The heatmap of this ModelExplanation.  # noqa: E501
        :type heatmap: str
        """
        self.openapi_types = {
            'model_architecture': str,
            'preprocessing_variant': str,
            'target_layer': str,
            'heatmap_overlay': str,
            'heatmap': str
        }

        self.attribute_map = {
            'model_architecture': 'model_architecture',
            'preprocessing_variant': 'preprocessing_variant',
            'target_layer': 'target_layer',
            'heatmap_overlay': 'heatmap_overlay',
            'heatmap': 'heatmap'
        }

        self._model_architecture = model_architecture
        self._preprocessing_variant = preprocessing_variant
        self._target_layer = target_layer
        self._heatmap_overlay = heatmap_overlay
        self._heatmap = heatmap

    @classmethod
    def from_dict(cls, dikt) -> 'ModelExplanation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelExplanation of this ModelExplanation.  # noqa: E501
        :rtype: ModelExplanation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_architecture(self) -> str:
        """Gets the model_architecture of this ModelExplanation.


        :return: The model_architecture of this ModelExplanation.
        :rtype: str
        """
        return self._model_architecture

    @model_architecture.setter
    def model_architecture(self, model_architecture: str):
        """Sets the model_architecture of this ModelExplanation.


        :param model_architecture: The model_architecture of this ModelExplanation.
        :type model_architecture: str
        """
        if model_architecture is None:
            raise ValueError("Invalid value for `model_architecture`, must not be `None`")  # noqa: E501

        self._model_architecture = model_architecture

    @property
    def preprocessing_variant(self) -> str:
        """Gets the preprocessing_variant of this ModelExplanation.

        Preprocessing variant the explained model consumed  # noqa: E501

        :return: The preprocessing_variant of this ModelExplanation.
        :rtype: str
        """
        return self._preprocessing_variant

    @preprocessing_variant.setter
    def preprocessing_variant(self, preprocessing_variant: str):
        """Sets the preprocessing_variant of this ModelExplanation.

        Preprocessing variant the explained model consumed  # noqa: E501

        :param preprocessing_variant: The preprocessing_variant of this ModelExplanation.
        :type preprocessing_variant: str
        """
        if preprocessing_variant is None:
            raise ValueError("Invalid value for `preprocessing_variant`, must not be `None`")  # noqa: E501

        self._preprocessing_variant = preprocessing_variant

    @property
    def target_layer(self) -> str:
        """Gets the target_layer of this ModelExplanation.

        Network layer the Grad-CAM was computed on  # noqa: E501

        :return: The target_layer of this ModelExplanation.
        :rtype: str
        """
        return self._target_layer

    @target_layer.setter
    def target_layer(self, target_layer: str):
        """Sets the target_layer of this ModelExplanation.

        Network layer the Grad-CAM was computed on  # noqa: E501

        :param target_layer: The target_layer of this ModelExplanation.
        :type target_layer: str
        """

        self._target_layer = target_layer

    @property
    def heatmap_overlay(self) -> str:
        """Gets the heatmap_overlay of this ModelExplanation.

        Base64-encoded JPEG - heatmap blended over the model input image  # noqa: E501

        :return: The heatmap_overlay of this ModelExplanation.
        :rtype: str
        """
        return self._heatmap_overlay

    @heatmap_overlay.setter
    def heatmap_overlay(self, heatmap_overlay: str):
        """Sets the heatmap_overlay of this ModelExplanation.

        Base64-encoded JPEG - heatmap blended over the model input image  # noqa: E501

        :param heatmap_overlay: The heatmap_overlay of this ModelExplanation.
        :type heatmap_overlay: str
        """
        if heatmap_overlay is None:
            raise ValueError("Invalid value for `heatmap_overlay`, must not be `None`")  # noqa: E501

        self._heatmap_overlay = heatmap_overlay

    @property
    def heatmap(self) -> str:
        """Gets the heatmap of this ModelExplanation.

        Base64-encoded JPEG - colorized Grad-CAM heatmap only  # noqa: E501

        :return: The heatmap of this ModelExplanation.
        :rtype: str
        """
        return self._heatmap

    @heatmap.setter
    def heatmap(self, heatmap: str):
        """Sets the heatmap of this ModelExplanation.

        Base64-encoded JPEG - colorized Grad-CAM heatmap only  # noqa: E501

        :param heatmap: The heatmap of this ModelExplanation.
        :type heatmap: str
        """
        if heatmap is None:
            raise ValueError("Invalid value for `heatmap`, must not be `None`")  # noqa: E501

        self._heatmap = heatmap
