from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.model_info_response_models_inner import ModelInfoResponseModelsInner
from ensemble_inference import util

from ensemble_inference.models.model_info_response_models_inner import ModelInfoResponseModelsInner  # noqa: E501

class ModelInfoResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, models=None, voting_strategy=None, device=None, total_models=None):  # noqa: E501
        """ModelInfoResponse - a model defined in OpenAPI

        :param models: The models of this ModelInfoResponse.  # noqa: E501
        :type models: List[ModelInfoResponseModelsInner]
        :param voting_strategy: The voting_strategy of this ModelInfoResponse.  # noqa: E501
        :type voting_strategy: str
        :param device: The device of this ModelInfoResponse.  # noqa: E501
        :type device: str
        :param total_models: The total_models of this ModelInfoResponse.  # noqa: E501
        :type total_models: int
        """
        self.openapi_types = {
            'models': List[ModelInfoResponseModelsInner],
            'voting_strategy': str,
            'device': str,
            'total_models': int
        }

        self.attribute_map = {
            'models': 'models',
            'voting_strategy': 'voting_strategy',
            'device': 'device',
            'total_models': 'total_models'
        }

        self._models = models
        self._voting_strategy = voting_strategy
        self._device = device
        self._total_models = total_models

    @classmethod
    def from_dict(cls, dikt) -> 'ModelInfoResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelInfoResponse of this ModelInfoResponse.  # noqa: E501
        :rtype: ModelInfoResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def models(self) -> List[ModelInfoResponseModelsInner]:
        """Gets the models of this ModelInfoResponse.


        :return: The models of this ModelInfoResponse.
        :rtype: List[ModelInfoResponseModelsInner]
        """
        return self._models

    @models.setter
    def models(self, models: List[ModelInfoResponseModelsInner]):
        """Sets the models of this ModelInfoResponse.


        :param models: The models of this ModelInfoResponse.
        :type models: List[ModelInfoResponseModelsInner]
        """

        self._models = models

    @property
    def voting_strategy(self) -> str:
        """Gets the voting_strategy of this ModelInfoResponse.


        :return: The voting_strategy of this ModelInfoResponse.
        :rtype: str
        """
        return self._voting_strategy

    @voting_strategy.setter
    def voting_strategy(self, voting_strategy: str):
        """Sets the voting_strategy of this ModelInfoResponse.


        :param voting_strategy: The voting_strategy of this ModelInfoResponse.
        :type voting_strategy: str
        """
        allowed_values = ["soft", "hard"]  # noqa: E501
        if voting_strategy not in allowed_values:
            raise ValueError(
                "Invalid value for `voting_strategy` ({0}), must be one of {1}"
                .format(voting_strategy, allowed_values)
            )

        self._voting_strategy = voting_strategy

    @property
    def device(self) -> str:
        """Gets the device of this ModelInfoResponse.


        :return: The device of this ModelInfoResponse.
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device: str):
        """Sets the device of this ModelInfoResponse.


        :param device: The device of this ModelInfoResponse.
        :type device: str
        """

        self._device = device

    @property
    def total_models(self) -> int:
        """Gets the total_models of this ModelInfoResponse.


        :return: The total_models of this ModelInfoResponse.
        :rtype: int
        """
        return self._total_models

    @total_models.setter
    def total_models(self, total_models: int):
        """Sets the total_models of this ModelInfoResponse.


        :param total_models: The total_models of this ModelInfoResponse.
        :type total_models: int
        """

        self._total_models = total_models
