from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ModelInfoResponseModelsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, architecture=None, dataset=None, preprocessing_variant=None, model_path=None, num_classes=None):  # noqa: E501
        """ModelInfoResponseModelsInner - a model defined in OpenAPI

        :param architecture: The architecture of this ModelInfoResponseModelsInner.  # noqa: E501
        :type architecture: str
        :param dataset: The dataset of this ModelInfoResponseModelsInner.  # noqa: E501
        :type dataset: str
        :param preprocessing_variant: The preprocessing_variant of this ModelInfoResponseModelsInner.  # noqa: E501
        :type preprocessing_variant: str
        :param model_path: The model_path of this ModelInfoResponseModelsInner.  # noqa: E501
        :type model_path: str
        :param num_classes: The num_classes of this ModelInfoResponseModelsInner.  # noqa: E501
        :type num_classes: int
        """
        self.openapi_types = {
            'architecture': str,
            'dataset': str,
            'preprocessing_variant': str,
            'model_path': str,
            'num_classes': int
        }

        self.attribute_map = {
            'architecture': 'architecture',
            'dataset': 'dataset',
            'preprocessing_variant': 'preprocessing_variant',
            'model_path': 'model_path',
            'num_classes': 'num_classes'
        }

        self._architecture = architecture
        self._dataset = dataset
        self._preprocessing_variant = preprocessing_variant
        self._model_path = model_path
        self._num_classes = num_classes

    @classmethod
    def from_dict(cls, dikt) -> 'ModelInfoResponseModelsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelInfoResponse_models_inner of this ModelInfoResponseModelsInner.  # noqa: E501
        :rtype: ModelInfoResponseModelsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def architecture(self) -> str:
        """Gets the architecture of this ModelInfoResponseModelsInner.


        :return: The architecture of this ModelInfoResponseModelsInner.
        :rtype: str
        """
        return self._architecture

    @architecture.setter
    def architecture(self, architecture: str):
        """Sets the architecture of this ModelInfoResponseModelsInner.


        :param architecture: The architecture of this ModelInfoResponseModelsInner.
        :type architecture: str
        """

        self._architecture = architecture

    @property
    def dataset(self) -> str:
        """Gets the dataset of this ModelInfoResponseModelsInner.


        :return: The dataset of this ModelInfoResponseModelsInner.
        :rtype: str
        """
        return self._dataset

    @dataset.setter
    def dataset(self, dataset: str):
        """Sets the dataset of this ModelInfoResponseModelsInner.


        :param dataset: The dataset of this ModelInfoResponseModelsInner.
        :type dataset: str
        """

        self._dataset = dataset

    @property
    def preprocessing_variant(self) -> str:
        """Gets the preprocessing_variant of this ModelInfoResponseModelsInner.


        :return: The preprocessing_variant of this ModelInfoResponseModelsInner.
        :rtype: str
        """
        return self._preprocessing_variant

    @preprocessing_variant.setter
    def preprocessing_variant(self, preprocessing_variant: str):
        """Sets the preprocessing_variant of this ModelInfoResponseModelsInner.


        :param preprocessing_variant: The preprocessing_variant of this ModelInfoResponseModelsInner.
        :type preprocessing_variant: str
        """

        self._preprocessing_variant = preprocessing_variant

    @property
    def model_path(self) -> str:
        """Gets the model_path of this ModelInfoResponseModelsInner.


        :return: The model_path of this ModelInfoResponseModelsInner.
        :rtype: str
        """
        return self._model_path

    @model_path.setter
    def model_path(self, model_path: str):
        """Sets the model_path of this ModelInfoResponseModelsInner.


        :param model_path: The model_path of this ModelInfoResponseModelsInner.
        :type model_path: str
        """

        self._model_path = model_path

    @property
    def num_classes(self) -> int:
        """Gets the num_classes of this ModelInfoResponseModelsInner.


        :return: The num_classes of this ModelInfoResponseModelsInner.
        :rtype: int
        """
        return self._num_classes

    @num_classes.setter
    def num_classes(self, num_classes: int):
        """Sets the num_classes of this ModelInfoResponseModelsInner.


        :param num_classes: The num_classes of this ModelInfoResponseModelsInner.
        :type num_classes: int
        """

        self._num_classes = num_classes
