from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class PreprocessResponseVariants(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, original=None, rgb_clahe=None, ben_graham=None, lab_clahe=None, max_green_gsc=None):  # noqa: E501
        """PreprocessResponseVariants - a model defined in OpenAPI

        :param original: The original of this PreprocessResponseVariants.  # noqa: E501
        :type original: str
        :param rgb_clahe: The rgb_clahe of this PreprocessResponseVariants.  # noqa: E501
        :type rgb_clahe: str
        :param ben_graham: The ben_graham of this PreprocessResponseVariants.  # noqa: E501
        :type ben_graham: str
        :param lab_clahe: The lab_clahe of this PreprocessResponseVariants.  # noqa: E501
        :type lab_clahe: str
        :param max_green_gsc: The max_green_gsc of this PreprocessResponseVariants.  # noqa: E501
        :type max_green_gsc: str
        """
        self.openapi_types = {
            'original': str,
            'rgb_clahe': str,
            'ben_graham': str,
            'lab_clahe': str,
            'max_green_gsc': str
        }

        self.attribute_map = {
            'original': 'original',
            'rgb_clahe': 'rgb_clahe',
            'ben_graham': 'ben_graham',
            'lab_clahe': 'lab_clahe',
            'max_green_gsc': 'max_green_gsc'
        }

        self._original = original
        self._rgb_clahe = rgb_clahe
        self._ben_graham = ben_graham
        self._lab_clahe = lab_clahe
        self._max_green_gsc = max_green_gsc

    @classmethod
    def from_dict(cls, dikt) -> 'PreprocessResponseVariants':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreprocessResponse_variants of this PreprocessResponseVariants.  # noqa: E501
        :rtype: PreprocessResponseVariants
        """
        return util.deserialize_model(dikt, cls)

    @property
    def original(self) -> str:
        """Gets the original of this PreprocessResponseVariants.


        :return: The original of this PreprocessResponseVariants.
        :rtype: str
        """
        return self._original

    @original.setter
    def original(self, original: str):
        """Sets the original of this PreprocessResponseVariants.


        :param original: The original of this PreprocessResponseVariants.
        :type original: str
        """

        self._original = original

    @property
    def rgb_clahe(self) -> str:
        """Gets the rgb_clahe of this PreprocessResponseVariants.


        :return: The rgb_clahe of this PreprocessResponseVariants.
        :rtype: str
        """
        return self._rgb_clahe

    @rgb_clahe.setter
    def rgb_clahe(self, rgb_clahe: str):
        """Sets the rgb_clahe of this PreprocessResponseVariants.


        :param rgb_clahe: The rgb_clahe of this PreprocessResponseVariants.
        :type rgb_clahe: str
        """

        self._rgb_clahe = rgb_clahe

    @property
    def ben_graham(self) -> str:
        """Gets the ben_graham of this PreprocessResponseVariants.


        :return: The ben_graham of this PreprocessResponseVariants.
        :rtype: str
        """
        return self._ben_graham

    @ben_graham.setter
    def ben_graham(self, ben_graham: str):
        """Sets the ben_graham of this PreprocessResponseVariants.


        :param ben_graham: The ben_graham of this PreprocessResponseVariants.
        :type ben_graham: str
        """

        self._ben_graham = ben_graham

    @property
    def lab_clahe(self) -> str:
        """Gets the lab_clahe of this PreprocessResponseVariants.


        :return: The lab_clahe of this PreprocessResponseVariants.
        :rtype: str
        """
        return self._lab_clahe

    @lab_clahe.setter
    def lab_clahe(self, lab_clahe: str):
        """Sets the lab_clahe of this PreprocessResponseVariants.


        :param lab_clahe: The lab_clahe of this PreprocessResponseVariants.
        :type lab_clahe: str
        """

        self._lab_clahe = lab_clahe

    @property
    def max_green_gsc(self) -> str:
        """Gets the max_green_gsc of this PreprocessResponseVariants.


        :return: The max_green_gsc of this PreprocessResponseVariants.
        :rtype: str
        """
        return self._max_green_gsc

    @max_green_gsc.setter
    def max_green_gsc(self, max_green_gsc: str):
        """Sets the max_green_gsc of this PreprocessResponseVariants.


        :param max_green_gsc: The max_green_gsc of this PreprocessResponseVariants.
        :type max_green_gsc: str
        """

        self._max_green_gsc = max_green_gsc
