from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class PreprocessedImages(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, original=None, rgb_clahe=None, min_pooling=None, lab_clahe=None, max_green_gsc=None):  # noqa: E501
        """PreprocessedImages - a model defined in OpenAPI

        :param original: The original of this PreprocessedImages.  # noqa: E501
        :type original: str
        :param rgb_clahe: The rgb_clahe of this PreprocessedImages.  # noqa: E501
        :type rgb_clahe: str
        :param min_pooling: The min_pooling of this PreprocessedImages.  # noqa: E501
        :type min_pooling: str
        :param lab_clahe: The lab_clahe of this PreprocessedImages.  # noqa: E501
        :type lab_clahe: str
        :param max_green_gsc: The max_green_gsc of this PreprocessedImages.  # noqa: E501
        :type max_green_gsc: str
        """
        self.openapi_types = {
            'original': str,
            'rgb_clahe': str,
            'min_pooling': str,
            'lab_clahe': str,
            'max_green_gsc': str
        }

        self.attribute_map = {
            'original': 'original',
            'rgb_clahe': 'rgb_clahe',
            'min_pooling': 'min_pooling',
            'lab_clahe': 'lab_clahe',
            'max_green_gsc': 'max_green_gsc'
        }

        self._original = original
        self._rgb_clahe = rgb_clahe
        self._min_pooling = min_pooling
        self._lab_clahe = lab_clahe
        self._max_green_gsc = max_green_gsc

    @classmethod
    def from_dict(cls, dikt) -> 'PreprocessedImages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreprocessedImages of this PreprocessedImages.  # noqa: E501
        :rtype: PreprocessedImages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def original(self) -> str:
        """Gets the original of this PreprocessedImages.

        Original image after standardization and clipping  # noqa: E501

        :return: The original of this PreprocessedImages.
        :rtype: str
        """
        return self._original

    @original.setter
    def original(self, original: str):
        """Sets the original of this PreprocessedImages.

        Original image after standardization and clipping  # noqa: E501

        :param original: The original of this PreprocessedImages.
        :type original: str
        """

        self._original = original

    @property
    def rgb_clahe(self) -> str:
        """Gets the rgb_clahe of this PreprocessedImages.

        RGB-CLAHE enhanced image  # noqa: E501

        :return: The rgb_clahe of this PreprocessedImages.
        :rtype: str
        """
        return self._rgb_clahe

    @rgb_clahe.setter
    def rgb_clahe(self, rgb_clahe: str):
        """Sets the rgb_clahe of this PreprocessedImages.

        RGB-CLAHE enhanced image  # noqa: E501

        :param rgb_clahe: The rgb_clahe of this PreprocessedImages.
        :type rgb_clahe: str
        """

        self._rgb_clahe = rgb_clahe

    @property
    def min_pooling(self) -> str:
        """Gets the min_pooling of this PreprocessedImages.

        Ben Graham/ Min pooling preprocessing variant  # noqa: E501

        :return: The min_pooling of this PreprocessedImages.
        :rtype: str
        """
        return self._min_pooling

    @min_pooling.setter
    def min_pooling(self, min_pooling: str):
        """Sets the min_pooling of this PreprocessedImages.

        Ben Graham/ Min pooling preprocessing variant  # noqa: E501

        :param min_pooling: The min_pooling of this PreprocessedImages.
        :type min_pooling: str
        """

        self._min_pooling = min_pooling

    @property
    def lab_clahe(self) -> str:
        """Gets the lab_clahe of this PreprocessedImages.

        Lab-CLAHE enhanced image  # noqa: E501

        :return: The lab_clahe of this PreprocessedImages.
        :rtype: str
        """
        return self._lab_clahe

    @lab_clahe.setter
    def lab_clahe(self, lab_clahe: str):
        """Sets the lab_clahe of this PreprocessedImages.

        Lab-CLAHE enhanced image  # noqa: E501

        :param lab_clahe: The lab_clahe of this PreprocessedImages.
        :type lab_clahe: str
        """

        self._lab_clahe = lab_clahe

    @property
    def max_green_gsc(self) -> str:
        """Gets the max_green_gsc of this PreprocessedImages.

        Max Green Grayscale converted image  # noqa: E501

        :return: The max_green_gsc of this PreprocessedImages.
        :rtype: str
        """
        return self._max_green_gsc

    @max_green_gsc.setter
    def max_green_gsc(self, max_green_gsc: str):
        """Sets the max_green_gsc of this PreprocessedImages.

        Max Green Grayscale converted image  # noqa: E501

        :param max_green_gsc: The max_green_gsc of this PreprocessedImages.
        :type max_green_gsc: str
        """

        self._max_green_gsc = max_green_gsc
