from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.operation_status import OperationStatus
from ensemble_inference.models.preprocess_response_metadata import PreprocessResponseMetadata
from ensemble_inference.models.preprocessed_images import PreprocessedImages
from ensemble_inference import util

from ensemble_inference.models.operation_status import OperationStatus  # noqa: E501
from ensemble_inference.models.preprocess_response_metadata import PreprocessResponseMetadata  # noqa: E501
from ensemble_inference.models.preprocessed_images import PreprocessedImages  # noqa: E501

class PreprocessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, preprocessed_images=None, metadata=None):  # noqa: E501
        """PreprocessResponse - a model defined in OpenAPI

        :param status: The status of this PreprocessResponse.  # noqa: E501
        :type status: OperationStatus
        :param preprocessed_images: The preprocessed_images of this PreprocessResponse.  # noqa: E501
        :type preprocessed_images: PreprocessedImages
        :param metadata: The metadata of this PreprocessResponse.  # noqa: E501
        :type metadata: PreprocessResponseMetadata
        """
        self.openapi_types = {
            'status': OperationStatus,
            'preprocessed_images': PreprocessedImages,
            'metadata': PreprocessResponseMetadata
        }

        self.attribute_map = {
            'status': 'status',
            'preprocessed_images': 'preprocessed_images',
            'metadata': 'metadata'
        }

        self._status = status
        self._preprocessed_images = preprocessed_images
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'PreprocessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreprocessResponse of this PreprocessResponse.  # noqa: E501
        :rtype: PreprocessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> OperationStatus:
        """Gets the status of this PreprocessResponse.


        :return: The status of this PreprocessResponse.
        :rtype: OperationStatus
        """
        return self._status

    @status.setter
    def status(self, status: OperationStatus):
        """Sets the status of this PreprocessResponse.


        :param status: The status of this PreprocessResponse.
        :type status: OperationStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def preprocessed_images(self) -> PreprocessedImages:
        """Gets the preprocessed_images of this PreprocessResponse.


        :return: The preprocessed_images of this PreprocessResponse.
        :rtype: PreprocessedImages
        """
        return self._preprocessed_images

    @preprocessed_images.setter
    def preprocessed_images(self, preprocessed_images: PreprocessedImages):
        """Sets the preprocessed_images of this PreprocessResponse.


        :param preprocessed_images: The preprocessed_images of this PreprocessResponse.
        :type preprocessed_images: PreprocessedImages
        """

        self._preprocessed_images = preprocessed_images

    @property
    def metadata(self) -> PreprocessResponseMetadata:
        """Gets the metadata of this PreprocessResponse.


        :return: The metadata of this PreprocessResponse.
        :rtype: PreprocessResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: PreprocessResponseMetadata):
        """Sets the metadata of this PreprocessResponse.


        :param metadata: The metadata of this PreprocessResponse.
        :type metadata: PreprocessResponseMetadata
        """

        self._metadata = metadata
