from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.preprocess_response_metadata import PreprocessResponseMetadata
from ensemble_inference.models.preprocess_response_variants import PreprocessResponseVariants
from ensemble_inference import util

from ensemble_inference.models.preprocess_response_metadata import PreprocessResponseMetadata  # noqa: E501
from ensemble_inference.models.preprocess_response_variants import PreprocessResponseVariants  # noqa: E501

class PreprocessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, processing_time_seconds=None, variants=None, metadata=None):  # noqa: E501
        """PreprocessResponse - a model defined in OpenAPI

        :param status: The status of this PreprocessResponse.  # noqa: E501
        :type status: str
        :param processing_time_seconds: The processing_time_seconds of this PreprocessResponse.  # noqa: E501
        :type processing_time_seconds: float
        :param variants: The variants of this PreprocessResponse.  # noqa: E501
        :type variants: PreprocessResponseVariants
        :param metadata: The metadata of this PreprocessResponse.  # noqa: E501
        :type metadata: PreprocessResponseMetadata
        """
        self.openapi_types = {
            'status': str,
            'processing_time_seconds': float,
            'variants': PreprocessResponseVariants,
            'metadata': PreprocessResponseMetadata
        }

        self.attribute_map = {
            'status': 'status',
            'processing_time_seconds': 'processing_time_seconds',
            'variants': 'variants',
            'metadata': 'metadata'
        }

        self._status = status
        self._processing_time_seconds = processing_time_seconds
        self._variants = variants
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'PreprocessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreprocessResponse of this PreprocessResponse.  # noqa: E501
        :rtype: PreprocessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this PreprocessResponse.


        :return: The status of this PreprocessResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this PreprocessResponse.


        :param status: The status of this PreprocessResponse.
        :type status: str
        """

        self._status = status

    @property
    def processing_time_seconds(self) -> float:
        """Gets the processing_time_seconds of this PreprocessResponse.


        :return: The processing_time_seconds of this PreprocessResponse.
        :rtype: float
        """
        return self._processing_time_seconds

    @processing_time_seconds.setter
    def processing_time_seconds(self, processing_time_seconds: float):
        """Sets the processing_time_seconds of this PreprocessResponse.


        :param processing_time_seconds: The processing_time_seconds of this PreprocessResponse.
        :type processing_time_seconds: float
        """

        self._processing_time_seconds = processing_time_seconds

    @property
    def variants(self) -> PreprocessResponseVariants:
        """Gets the variants of this PreprocessResponse.


        :return: The variants of this PreprocessResponse.
        :rtype: PreprocessResponseVariants
        """
        return self._variants

    @variants.setter
    def variants(self, variants: PreprocessResponseVariants):
        """Sets the variants of this PreprocessResponse.


        :param variants: The variants of this PreprocessResponse.
        :type variants: PreprocessResponseVariants
        """

        self._variants = variants

    @property
    def metadata(self) -> PreprocessResponseMetadata:
        """Gets the metadata of this PreprocessResponse.


        :return: The metadata of this PreprocessResponse.
        :rtype: PreprocessResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: PreprocessResponseMetadata):
        """Sets the metadata of this PreprocessResponse.


        :param metadata: The metadata of this PreprocessResponse.
        :type metadata: PreprocessResponseMetadata
        """

        self._metadata = metadata
