from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class PreprocessResponseMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, original_size=None, processed_size=None, variant_count=None):  # noqa: E501
        """PreprocessResponseMetadata - a model defined in OpenAPI

        :param original_size: The original_size of this PreprocessResponseMetadata.  # noqa: E501
        :type original_size: List[int]
        :param processed_size: The processed_size of this PreprocessResponseMetadata.  # noqa: E501
        :type processed_size: List[int]
        :param variant_count: The variant_count of this PreprocessResponseMetadata.  # noqa: E501
        :type variant_count: int
        """
        self.openapi_types = {
            'original_size': List[int],
            'processed_size': List[int],
            'variant_count': int
        }

        self.attribute_map = {
            'original_size': 'original_size',
            'processed_size': 'processed_size',
            'variant_count': 'variant_count'
        }

        self._original_size = original_size
        self._processed_size = processed_size
        self._variant_count = variant_count

    @classmethod
    def from_dict(cls, dikt) -> 'PreprocessResponseMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreprocessResponse_metadata of this PreprocessResponseMetadata.  # noqa: E501
        :rtype: PreprocessResponseMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def original_size(self) -> List[int]:
        """Gets the original_size of this PreprocessResponseMetadata.


        :return: The original_size of this PreprocessResponseMetadata.
        :rtype: List[int]
        """
        return self._original_size

    @original_size.setter
    def original_size(self, original_size: List[int]):
        """Sets the original_size of this PreprocessResponseMetadata.


        :param original_size: The original_size of this PreprocessResponseMetadata.
        :type original_size: List[int]
        """

        self._original_size = original_size

    @property
    def processed_size(self) -> List[int]:
        """Gets the processed_size of this PreprocessResponseMetadata.


        :return: The processed_size of this PreprocessResponseMetadata.
        :rtype: List[int]
        """
        return self._processed_size

    @processed_size.setter
    def processed_size(self, processed_size: List[int]):
        """Sets the processed_size of this PreprocessResponseMetadata.


        :param processed_size: The processed_size of this PreprocessResponseMetadata.
        :type processed_size: List[int]
        """

        self._processed_size = processed_size

    @property
    def variant_count(self) -> int:
        """Gets the variant_count of this PreprocessResponseMetadata.


        :return: The variant_count of this PreprocessResponseMetadata.
        :rtype: int
        """
        return self._variant_count

    @variant_count.setter
    def variant_count(self, variant_count: int):
        """Sets the variant_count of this PreprocessResponseMetadata.


        :param variant_count: The variant_count of this PreprocessResponseMetadata.
        :type variant_count: int
        """

        self._variant_count = variant_count
