from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.image_properties import ImageProperties
from ensemble_inference import util

from ensemble_inference.models.image_properties import ImageProperties  # noqa: E501

class PreprocessResponseMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_properties=None, processing_time_seconds=None, variant_count=None):  # noqa: E501
        """PreprocessResponseMetadata - a model defined in OpenAPI

        :param image_properties: The image_properties of this PreprocessResponseMetadata.  # noqa: E501
        :type image_properties: ImageProperties
        :param processing_time_seconds: The processing_time_seconds of this PreprocessResponseMetadata.  # noqa: E501
        :type processing_time_seconds: float
        :param variant_count: The variant_count of this PreprocessResponseMetadata.  # noqa: E501
        :type variant_count: int
        """
        self.openapi_types = {
            'image_properties': ImageProperties,
            'processing_time_seconds': float,
            'variant_count': int
        }

        self.attribute_map = {
            'image_properties': 'image_properties',
            'processing_time_seconds': 'processing_time_seconds',
            'variant_count': 'variant_count'
        }

        self._image_properties = image_properties
        self._processing_time_seconds = processing_time_seconds
        self._variant_count = variant_count

    @classmethod
    def from_dict(cls, dikt) -> 'PreprocessResponseMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreprocessResponse_metadata of this PreprocessResponseMetadata.  # noqa: E501
        :rtype: PreprocessResponseMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_properties(self) -> ImageProperties:
        """Gets the image_properties of this PreprocessResponseMetadata.


        :return: The image_properties of this PreprocessResponseMetadata.
        :rtype: ImageProperties
        """
        return self._image_properties

    @image_properties.setter
    def image_properties(self, image_properties: ImageProperties):
        """Sets the image_properties of this PreprocessResponseMetadata.


        :param image_properties: The image_properties of this PreprocessResponseMetadata.
        :type image_properties: ImageProperties
        """

        self._image_properties = image_properties

    @property
    def processing_time_seconds(self) -> float:
        """Gets the processing_time_seconds of this PreprocessResponseMetadata.


        :return: The processing_time_seconds of this PreprocessResponseMetadata.
        :rtype: float
        """
        return self._processing_time_seconds

    @processing_time_seconds.setter
    def processing_time_seconds(self, processing_time_seconds: float):
        """Sets the processing_time_seconds of this PreprocessResponseMetadata.


        :param processing_time_seconds: The processing_time_seconds of this PreprocessResponseMetadata.
        :type processing_time_seconds: float
        """

        self._processing_time_seconds = processing_time_seconds

    @property
    def variant_count(self) -> int:
        """Gets the variant_count of this PreprocessResponseMetadata.


        :return: The variant_count of this PreprocessResponseMetadata.
        :rtype: int
        """
        return self._variant_count

    @variant_count.setter
    def variant_count(self, variant_count: int):
        """Sets the variant_count of this PreprocessResponseMetadata.


        :param variant_count: The variant_count of this PreprocessResponseMetadata.
        :type variant_count: int
        """

        self._variant_count = variant_count
