from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.classification_result import ClassificationResult
from ensemble_inference.models.process_response_metadata import ProcessResponseMetadata
from ensemble_inference.models.processing_times import ProcessingTimes
from ensemble_inference import util

from ensemble_inference.models.classification_result import ClassificationResult  # noqa: E501
from ensemble_inference.models.process_response_metadata import ProcessResponseMetadata  # noqa: E501
from ensemble_inference.models.processing_times import ProcessingTimes  # noqa: E501

class ProcessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, request_id=None, timestamp_utc=None, image_name=None, cached=None, cache_hit=None, processing_times=None, metadata=None, result=None, preprocessed_images=None):  # noqa: E501
        """ProcessResponse - a model defined in OpenAPI

        :param status: The status of this ProcessResponse.  # noqa: E501
        :type status: str
        :param request_id: The request_id of this ProcessResponse.  # noqa: E501
        :type request_id: str
        :param timestamp_utc: The timestamp_utc of this ProcessResponse.  # noqa: E501
        :type timestamp_utc: datetime
        :param image_name: The image_name of this ProcessResponse.  # noqa: E501
        :type image_name: str
        :param cached: The cached of this ProcessResponse.  # noqa: E501
        :type cached: bool
        :param cache_hit: The cache_hit of this ProcessResponse.  # noqa: E501
        :type cache_hit: bool
        :param processing_times: The processing_times of this ProcessResponse.  # noqa: E501
        :type processing_times: ProcessingTimes
        :param metadata: The metadata of this ProcessResponse.  # noqa: E501
        :type metadata: ProcessResponseMetadata
        :param result: The result of this ProcessResponse.  # noqa: E501
        :type result: ClassificationResult
        :param preprocessed_images: The preprocessed_images of this ProcessResponse.  # noqa: E501
        :type preprocessed_images: Dict[str, str]
        """
        self.openapi_types = {
            'status': str,
            'request_id': str,
            'timestamp_utc': datetime,
            'image_name': str,
            'cached': bool,
            'cache_hit': bool,
            'processing_times': ProcessingTimes,
            'metadata': ProcessResponseMetadata,
            'result': ClassificationResult,
            'preprocessed_images': Dict[str, str]
        }

        self.attribute_map = {
            'status': 'status',
            'request_id': 'request_id',
            'timestamp_utc': 'timestamp_utc',
            'image_name': 'image_name',
            'cached': 'cached',
            'cache_hit': 'cache_hit',
            'processing_times': 'processing_times',
            'metadata': 'metadata',
            'result': 'result',
            'preprocessed_images': 'preprocessed_images'
        }

        self._status = status
        self._request_id = request_id
        self._timestamp_utc = timestamp_utc
        self._image_name = image_name
        self._cached = cached
        self._cache_hit = cache_hit
        self._processing_times = processing_times
        self._metadata = metadata
        self._result = result
        self._preprocessed_images = preprocessed_images

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessResponse of this ProcessResponse.  # noqa: E501
        :rtype: ProcessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this ProcessResponse.


        :return: The status of this ProcessResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ProcessResponse.


        :param status: The status of this ProcessResponse.
        :type status: str
        """
        allowed_values = ["SUCCESS"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def request_id(self) -> str:
        """Gets the request_id of this ProcessResponse.

        Unique request identifier  # noqa: E501

        :return: The request_id of this ProcessResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this ProcessResponse.

        Unique request identifier  # noqa: E501

        :param request_id: The request_id of this ProcessResponse.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def timestamp_utc(self) -> datetime:
        """Gets the timestamp_utc of this ProcessResponse.

        UTC timestamp in ISO 8601 format  # noqa: E501

        :return: The timestamp_utc of this ProcessResponse.
        :rtype: datetime
        """
        return self._timestamp_utc

    @timestamp_utc.setter
    def timestamp_utc(self, timestamp_utc: datetime):
        """Sets the timestamp_utc of this ProcessResponse.

        UTC timestamp in ISO 8601 format  # noqa: E501

        :param timestamp_utc: The timestamp_utc of this ProcessResponse.
        :type timestamp_utc: datetime
        """
        if timestamp_utc is None:
            raise ValueError("Invalid value for `timestamp_utc`, must not be `None`")  # noqa: E501

        self._timestamp_utc = timestamp_utc

    @property
    def image_name(self) -> str:
        """Gets the image_name of this ProcessResponse.


        :return: The image_name of this ProcessResponse.
        :rtype: str
        """
        return self._image_name

    @image_name.setter
    def image_name(self, image_name: str):
        """Sets the image_name of this ProcessResponse.


        :param image_name: The image_name of this ProcessResponse.
        :type image_name: str
        """
        if image_name is None:
            raise ValueError("Invalid value for `image_name`, must not be `None`")  # noqa: E501

        self._image_name = image_name

    @property
    def cached(self) -> bool:
        """Gets the cached of this ProcessResponse.

        Whether result was retrieved from cache  # noqa: E501

        :return: The cached of this ProcessResponse.
        :rtype: bool
        """
        return self._cached

    @cached.setter
    def cached(self, cached: bool):
        """Sets the cached of this ProcessResponse.

        Whether result was retrieved from cache  # noqa: E501

        :param cached: The cached of this ProcessResponse.
        :type cached: bool
        """
        if cached is None:
            raise ValueError("Invalid value for `cached`, must not be `None`")  # noqa: E501

        self._cached = cached

    @property
    def cache_hit(self) -> bool:
        """Gets the cache_hit of this ProcessResponse.

        Cache hit indicator  # noqa: E501

        :return: The cache_hit of this ProcessResponse.
        :rtype: bool
        """
        return self._cache_hit

    @cache_hit.setter
    def cache_hit(self, cache_hit: bool):
        """Sets the cache_hit of this ProcessResponse.

        Cache hit indicator  # noqa: E501

        :param cache_hit: The cache_hit of this ProcessResponse.
        :type cache_hit: bool
        """
        if cache_hit is None:
            raise ValueError("Invalid value for `cache_hit`, must not be `None`")  # noqa: E501

        self._cache_hit = cache_hit

    @property
    def processing_times(self) -> ProcessingTimes:
        """Gets the processing_times of this ProcessResponse.


        :return: The processing_times of this ProcessResponse.
        :rtype: ProcessingTimes
        """
        return self._processing_times

    @processing_times.setter
    def processing_times(self, processing_times: ProcessingTimes):
        """Sets the processing_times of this ProcessResponse.


        :param processing_times: The processing_times of this ProcessResponse.
        :type processing_times: ProcessingTimes
        """
        if processing_times is None:
            raise ValueError("Invalid value for `processing_times`, must not be `None`")  # noqa: E501

        self._processing_times = processing_times

    @property
    def metadata(self) -> ProcessResponseMetadata:
        """Gets the metadata of this ProcessResponse.


        :return: The metadata of this ProcessResponse.
        :rtype: ProcessResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: ProcessResponseMetadata):
        """Sets the metadata of this ProcessResponse.


        :param metadata: The metadata of this ProcessResponse.
        :type metadata: ProcessResponseMetadata
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    @property
    def result(self) -> ClassificationResult:
        """Gets the result of this ProcessResponse.


        :return: The result of this ProcessResponse.
        :rtype: ClassificationResult
        """
        return self._result

    @result.setter
    def result(self, result: ClassificationResult):
        """Sets the result of this ProcessResponse.


        :param result: The result of this ProcessResponse.
        :type result: ClassificationResult
        """

        self._result = result

    @property
    def preprocessed_images(self) -> Dict[str, str]:
        """Gets the preprocessed_images of this ProcessResponse.

        Optional - included only if include_images=true  # noqa: E501

        :return: The preprocessed_images of this ProcessResponse.
        :rtype: Dict[str, str]
        """
        return self._preprocessed_images

    @preprocessed_images.setter
    def preprocessed_images(self, preprocessed_images: Dict[str, str]):
        """Sets the preprocessed_images of this ProcessResponse.

        Optional - included only if include_images=true  # noqa: E501

        :param preprocessed_images: The preprocessed_images of this ProcessResponse.
        :type preprocessed_images: Dict[str, str]
        """

        self._preprocessed_images = preprocessed_images
