from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.model_configuration import ModelConfiguration
from ensemble_inference.models.version_info import VersionInfo
from ensemble_inference import util

from ensemble_inference.models.model_configuration import ModelConfiguration  # noqa: E501
from ensemble_inference.models.version_info import VersionInfo  # noqa: E501

class ProcessMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_id=None, timestamp_utc=None, model_configuration=None, version_info=None):  # noqa: E501
        """ProcessMetadata - a model defined in OpenAPI

        :param request_id: The request_id of this ProcessMetadata.  # noqa: E501
        :type request_id: str
        :param timestamp_utc: The timestamp_utc of this ProcessMetadata.  # noqa: E501
        :type timestamp_utc: datetime
        :param model_configuration: The model_configuration of this ProcessMetadata.  # noqa: E501
        :type model_configuration: ModelConfiguration
        :param version_info: The version_info of this ProcessMetadata.  # noqa: E501
        :type version_info: VersionInfo
        """
        self.openapi_types = {
            'request_id': str,
            'timestamp_utc': datetime,
            'model_configuration': ModelConfiguration,
            'version_info': VersionInfo
        }

        self.attribute_map = {
            'request_id': 'request_id',
            'timestamp_utc': 'timestamp_utc',
            'model_configuration': 'model_configuration',
            'version_info': 'version_info'
        }

        self._request_id = request_id
        self._timestamp_utc = timestamp_utc
        self._model_configuration = model_configuration
        self._version_info = version_info

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessMetadata of this ProcessMetadata.  # noqa: E501
        :rtype: ProcessMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self) -> str:
        """Gets the request_id of this ProcessMetadata.

        Unique request identifier  # noqa: E501

        :return: The request_id of this ProcessMetadata.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this ProcessMetadata.

        Unique request identifier  # noqa: E501

        :param request_id: The request_id of this ProcessMetadata.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def timestamp_utc(self) -> datetime:
        """Gets the timestamp_utc of this ProcessMetadata.

        UTC timestamp in ISO 8601 format  # noqa: E501

        :return: The timestamp_utc of this ProcessMetadata.
        :rtype: datetime
        """
        return self._timestamp_utc

    @timestamp_utc.setter
    def timestamp_utc(self, timestamp_utc: datetime):
        """Sets the timestamp_utc of this ProcessMetadata.

        UTC timestamp in ISO 8601 format  # noqa: E501

        :param timestamp_utc: The timestamp_utc of this ProcessMetadata.
        :type timestamp_utc: datetime
        """
        if timestamp_utc is None:
            raise ValueError("Invalid value for `timestamp_utc`, must not be `None`")  # noqa: E501

        self._timestamp_utc = timestamp_utc

    @property
    def model_configuration(self) -> ModelConfiguration:
        """Gets the model_configuration of this ProcessMetadata.


        :return: The model_configuration of this ProcessMetadata.
        :rtype: ModelConfiguration
        """
        return self._model_configuration

    @model_configuration.setter
    def model_configuration(self, model_configuration: ModelConfiguration):
        """Sets the model_configuration of this ProcessMetadata.


        :param model_configuration: The model_configuration of this ProcessMetadata.
        :type model_configuration: ModelConfiguration
        """

        self._model_configuration = model_configuration

    @property
    def version_info(self) -> VersionInfo:
        """Gets the version_info of this ProcessMetadata.


        :return: The version_info of this ProcessMetadata.
        :rtype: VersionInfo
        """
        return self._version_info

    @version_info.setter
    def version_info(self, version_info: VersionInfo):
        """Sets the version_info of this ProcessMetadata.


        :param version_info: The version_info of this ProcessMetadata.
        :type version_info: VersionInfo
        """
        if version_info is None:
            raise ValueError("Invalid value for `version_info`, must not be `None`")  # noqa: E501

        self._version_info = version_info
