from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class ProcessingTimes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _00_preprocessing_ms=None, _01_inference_ms=None, total_ms=None, per_image_ms=None):  # noqa: E501
        """ProcessingTimes - a model defined in OpenAPI

        :param _00_preprocessing_ms: The _00_preprocessing_ms of this ProcessingTimes.  # noqa: E501
        :type _00_preprocessing_ms: float
        :param _01_inference_ms: The _01_inference_ms of this ProcessingTimes.  # noqa: E501
        :type _01_inference_ms: float
        :param total_ms: The total_ms of this ProcessingTimes.  # noqa: E501
        :type total_ms: float
        :param per_image_ms: The per_image_ms of this ProcessingTimes.  # noqa: E501
        :type per_image_ms: float
        """
        self.openapi_types = {
            '_00_preprocessing_ms': float,
            '_01_inference_ms': float,
            'total_ms': float,
            'per_image_ms': float
        }

        self.attribute_map = {
            '_00_preprocessing_ms': '00_preprocessing_ms',
            '_01_inference_ms': '01_inference_ms',
            'total_ms': 'total_ms',
            'per_image_ms': 'per_image_ms'
        }

        self.__00_preprocessing_ms = _00_preprocessing_ms
        self.__01_inference_ms = _01_inference_ms
        self._total_ms = total_ms
        self._per_image_ms = per_image_ms

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessingTimes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessingTimes of this ProcessingTimes.  # noqa: E501
        :rtype: ProcessingTimes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _00_preprocessing_ms(self) -> float:
        """Gets the _00_preprocessing_ms of this ProcessingTimes.

        Preprocessing time in milliseconds  # noqa: E501

        :return: The _00_preprocessing_ms of this ProcessingTimes.
        :rtype: float
        """
        return self.__00_preprocessing_ms

    @_00_preprocessing_ms.setter
    def _00_preprocessing_ms(self, _00_preprocessing_ms: float):
        """Sets the _00_preprocessing_ms of this ProcessingTimes.

        Preprocessing time in milliseconds  # noqa: E501

        :param _00_preprocessing_ms: The _00_preprocessing_ms of this ProcessingTimes.
        :type _00_preprocessing_ms: float
        """
        if _00_preprocessing_ms is None:
            raise ValueError("Invalid value for `_00_preprocessing_ms`, must not be `None`")  # noqa: E501

        self.__00_preprocessing_ms = _00_preprocessing_ms

    @property
    def _01_inference_ms(self) -> float:
        """Gets the _01_inference_ms of this ProcessingTimes.

        Inference time in milliseconds  # noqa: E501

        :return: The _01_inference_ms of this ProcessingTimes.
        :rtype: float
        """
        return self.__01_inference_ms

    @_01_inference_ms.setter
    def _01_inference_ms(self, _01_inference_ms: float):
        """Sets the _01_inference_ms of this ProcessingTimes.

        Inference time in milliseconds  # noqa: E501

        :param _01_inference_ms: The _01_inference_ms of this ProcessingTimes.
        :type _01_inference_ms: float
        """
        if _01_inference_ms is None:
            raise ValueError("Invalid value for `_01_inference_ms`, must not be `None`")  # noqa: E501

        self.__01_inference_ms = _01_inference_ms

    @property
    def total_ms(self) -> float:
        """Gets the total_ms of this ProcessingTimes.

        Total processing time in milliseconds  # noqa: E501

        :return: The total_ms of this ProcessingTimes.
        :rtype: float
        """
        return self._total_ms

    @total_ms.setter
    def total_ms(self, total_ms: float):
        """Sets the total_ms of this ProcessingTimes.

        Total processing time in milliseconds  # noqa: E501

        :param total_ms: The total_ms of this ProcessingTimes.
        :type total_ms: float
        """
        if total_ms is None:
            raise ValueError("Invalid value for `total_ms`, must not be `None`")  # noqa: E501

        self._total_ms = total_ms

    @property
    def per_image_ms(self) -> float:
        """Gets the per_image_ms of this ProcessingTimes.

        Average time per image in milliseconds  # noqa: E501

        :return: The per_image_ms of this ProcessingTimes.
        :rtype: float
        """
        return self._per_image_ms

    @per_image_ms.setter
    def per_image_ms(self, per_image_ms: float):
        """Sets the per_image_ms of this ProcessingTimes.

        Average time per image in milliseconds  # noqa: E501

        :param per_image_ms: The per_image_ms of this ProcessingTimes.
        :type per_image_ms: float
        """
        if per_image_ms is None:
            raise ValueError("Invalid value for `per_image_ms`, must not be `None`")  # noqa: E501

        self._per_image_ms = per_image_ms
