from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.process_metadata import ProcessMetadata
from ensemble_inference.models.process_result import ProcessResult
from ensemble_inference import util

from ensemble_inference.models.process_metadata import ProcessMetadata  # noqa: E501
from ensemble_inference.models.process_result import ProcessResult  # noqa: E501

class ProcessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, process_metadata=None, process_result=None):  # noqa: E501
        """ProcessResponse - a model defined in OpenAPI

        :param process_metadata: The process_metadata of this ProcessResponse.  # noqa: E501
        :type process_metadata: ProcessMetadata
        :param process_result: The process_result of this ProcessResponse.  # noqa: E501
        :type process_result: ProcessResult
        """
        self.openapi_types = {
            'process_metadata': ProcessMetadata,
            'process_result': ProcessResult
        }

        self.attribute_map = {
            'process_metadata': 'process_metadata',
            'process_result': 'process_result'
        }

        self._process_metadata = process_metadata
        self._process_result = process_result

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessResponse of this ProcessResponse.  # noqa: E501
        :rtype: ProcessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def process_metadata(self) -> ProcessMetadata:
        """Gets the process_metadata of this ProcessResponse.


        :return: The process_metadata of this ProcessResponse.
        :rtype: ProcessMetadata
        """
        return self._process_metadata

    @process_metadata.setter
    def process_metadata(self, process_metadata: ProcessMetadata):
        """Sets the process_metadata of this ProcessResponse.


        :param process_metadata: The process_metadata of this ProcessResponse.
        :type process_metadata: ProcessMetadata
        """
        if process_metadata is None:
            raise ValueError("Invalid value for `process_metadata`, must not be `None`")  # noqa: E501

        self._process_metadata = process_metadata

    @property
    def process_result(self) -> ProcessResult:
        """Gets the process_result of this ProcessResponse.


        :return: The process_result of this ProcessResponse.
        :rtype: ProcessResult
        """
        return self._process_result

    @process_result.setter
    def process_result(self, process_result: ProcessResult):
        """Sets the process_result of this ProcessResponse.


        :param process_result: The process_result of this ProcessResponse.
        :type process_result: ProcessResult
        """
        if process_result is None:
            raise ValueError("Invalid value for `process_result`, must not be `None`")  # noqa: E501

        self._process_result = process_result
