from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference.models.image_properties import ImageProperties
from ensemble_inference.models.model_configuration import ModelConfiguration
from ensemble_inference.models.version_info import VersionInfo
from ensemble_inference import util

from ensemble_inference.models.image_properties import ImageProperties  # noqa: E501
from ensemble_inference.models.model_configuration import ModelConfiguration  # noqa: E501
from ensemble_inference.models.version_info import VersionInfo  # noqa: E501

class ProcessResponseMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_properties=None, version_info=None, model_configuration=None):  # noqa: E501
        """ProcessResponseMetadata - a model defined in OpenAPI

        :param image_properties: The image_properties of this ProcessResponseMetadata.  # noqa: E501
        :type image_properties: ImageProperties
        :param version_info: The version_info of this ProcessResponseMetadata.  # noqa: E501
        :type version_info: VersionInfo
        :param model_configuration: The model_configuration of this ProcessResponseMetadata.  # noqa: E501
        :type model_configuration: ModelConfiguration
        """
        self.openapi_types = {
            'image_properties': ImageProperties,
            'version_info': VersionInfo,
            'model_configuration': ModelConfiguration
        }

        self.attribute_map = {
            'image_properties': 'image_properties',
            'version_info': 'version_info',
            'model_configuration': 'model_configuration'
        }

        self._image_properties = image_properties
        self._version_info = version_info
        self._model_configuration = model_configuration

    @classmethod
    def from_dict(cls, dikt) -> 'ProcessResponseMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProcessResponse_metadata of this ProcessResponseMetadata.  # noqa: E501
        :rtype: ProcessResponseMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_properties(self) -> ImageProperties:
        """Gets the image_properties of this ProcessResponseMetadata.


        :return: The image_properties of this ProcessResponseMetadata.
        :rtype: ImageProperties
        """
        return self._image_properties

    @image_properties.setter
    def image_properties(self, image_properties: ImageProperties):
        """Sets the image_properties of this ProcessResponseMetadata.


        :param image_properties: The image_properties of this ProcessResponseMetadata.
        :type image_properties: ImageProperties
        """
        if image_properties is None:
            raise ValueError("Invalid value for `image_properties`, must not be `None`")  # noqa: E501

        self._image_properties = image_properties

    @property
    def version_info(self) -> VersionInfo:
        """Gets the version_info of this ProcessResponseMetadata.


        :return: The version_info of this ProcessResponseMetadata.
        :rtype: VersionInfo
        """
        return self._version_info

    @version_info.setter
    def version_info(self, version_info: VersionInfo):
        """Sets the version_info of this ProcessResponseMetadata.


        :param version_info: The version_info of this ProcessResponseMetadata.
        :type version_info: VersionInfo
        """
        if version_info is None:
            raise ValueError("Invalid value for `version_info`, must not be `None`")  # noqa: E501

        self._version_info = version_info

    @property
    def model_configuration(self) -> ModelConfiguration:
        """Gets the model_configuration of this ProcessResponseMetadata.


        :return: The model_configuration of this ProcessResponseMetadata.
        :rtype: ModelConfiguration
        """
        return self._model_configuration

    @model_configuration.setter
    def model_configuration(self, model_configuration: ModelConfiguration):
        """Sets the model_configuration of this ProcessResponseMetadata.


        :param model_configuration: The model_configuration of this ProcessResponseMetadata.
        :type model_configuration: ModelConfiguration
        """

        self._model_configuration = model_configuration
