from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class StatsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uptime_seconds=None, uptime_formatted=None, total_requests=None, preprocessing_requests=None, classification_requests=None, errors=None, requests_per_minute=None):  # noqa: E501
        """StatsResponse - a model defined in OpenAPI

        :param uptime_seconds: The uptime_seconds of this StatsResponse.  # noqa: E501
        :type uptime_seconds: float
        :param uptime_formatted: The uptime_formatted of this StatsResponse.  # noqa: E501
        :type uptime_formatted: str
        :param total_requests: The total_requests of this StatsResponse.  # noqa: E501
        :type total_requests: int
        :param preprocessing_requests: The preprocessing_requests of this StatsResponse.  # noqa: E501
        :type preprocessing_requests: int
        :param classification_requests: The classification_requests of this StatsResponse.  # noqa: E501
        :type classification_requests: int
        :param errors: The errors of this StatsResponse.  # noqa: E501
        :type errors: int
        :param requests_per_minute: The requests_per_minute of this StatsResponse.  # noqa: E501
        :type requests_per_minute: float
        """
        self.openapi_types = {
            'uptime_seconds': float,
            'uptime_formatted': str,
            'total_requests': int,
            'preprocessing_requests': int,
            'classification_requests': int,
            'errors': int,
            'requests_per_minute': float
        }

        self.attribute_map = {
            'uptime_seconds': 'uptime_seconds',
            'uptime_formatted': 'uptime_formatted',
            'total_requests': 'total_requests',
            'preprocessing_requests': 'preprocessing_requests',
            'classification_requests': 'classification_requests',
            'errors': 'errors',
            'requests_per_minute': 'requests_per_minute'
        }

        self._uptime_seconds = uptime_seconds
        self._uptime_formatted = uptime_formatted
        self._total_requests = total_requests
        self._preprocessing_requests = preprocessing_requests
        self._classification_requests = classification_requests
        self._errors = errors
        self._requests_per_minute = requests_per_minute

    @classmethod
    def from_dict(cls, dikt) -> 'StatsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StatsResponse of this StatsResponse.  # noqa: E501
        :rtype: StatsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uptime_seconds(self) -> float:
        """Gets the uptime_seconds of this StatsResponse.


        :return: The uptime_seconds of this StatsResponse.
        :rtype: float
        """
        return self._uptime_seconds

    @uptime_seconds.setter
    def uptime_seconds(self, uptime_seconds: float):
        """Sets the uptime_seconds of this StatsResponse.


        :param uptime_seconds: The uptime_seconds of this StatsResponse.
        :type uptime_seconds: float
        """

        self._uptime_seconds = uptime_seconds

    @property
    def uptime_formatted(self) -> str:
        """Gets the uptime_formatted of this StatsResponse.


        :return: The uptime_formatted of this StatsResponse.
        :rtype: str
        """
        return self._uptime_formatted

    @uptime_formatted.setter
    def uptime_formatted(self, uptime_formatted: str):
        """Sets the uptime_formatted of this StatsResponse.


        :param uptime_formatted: The uptime_formatted of this StatsResponse.
        :type uptime_formatted: str
        """

        self._uptime_formatted = uptime_formatted

    @property
    def total_requests(self) -> int:
        """Gets the total_requests of this StatsResponse.


        :return: The total_requests of this StatsResponse.
        :rtype: int
        """
        return self._total_requests

    @total_requests.setter
    def total_requests(self, total_requests: int):
        """Sets the total_requests of this StatsResponse.


        :param total_requests: The total_requests of this StatsResponse.
        :type total_requests: int
        """

        self._total_requests = total_requests

    @property
    def preprocessing_requests(self) -> int:
        """Gets the preprocessing_requests of this StatsResponse.


        :return: The preprocessing_requests of this StatsResponse.
        :rtype: int
        """
        return self._preprocessing_requests

    @preprocessing_requests.setter
    def preprocessing_requests(self, preprocessing_requests: int):
        """Sets the preprocessing_requests of this StatsResponse.


        :param preprocessing_requests: The preprocessing_requests of this StatsResponse.
        :type preprocessing_requests: int
        """

        self._preprocessing_requests = preprocessing_requests

    @property
    def classification_requests(self) -> int:
        """Gets the classification_requests of this StatsResponse.


        :return: The classification_requests of this StatsResponse.
        :rtype: int
        """
        return self._classification_requests

    @classification_requests.setter
    def classification_requests(self, classification_requests: int):
        """Sets the classification_requests of this StatsResponse.


        :param classification_requests: The classification_requests of this StatsResponse.
        :type classification_requests: int
        """

        self._classification_requests = classification_requests

    @property
    def errors(self) -> int:
        """Gets the errors of this StatsResponse.


        :return: The errors of this StatsResponse.
        :rtype: int
        """
        return self._errors

    @errors.setter
    def errors(self, errors: int):
        """Sets the errors of this StatsResponse.


        :param errors: The errors of this StatsResponse.
        :type errors: int
        """

        self._errors = errors

    @property
    def requests_per_minute(self) -> float:
        """Gets the requests_per_minute of this StatsResponse.


        :return: The requests_per_minute of this StatsResponse.
        :rtype: float
        """
        return self._requests_per_minute

    @requests_per_minute.setter
    def requests_per_minute(self, requests_per_minute: float):
        """Sets the requests_per_minute of this StatsResponse.


        :param requests_per_minute: The requests_per_minute of this StatsResponse.
        :type requests_per_minute: float
        """

        self._requests_per_minute = requests_per_minute
