from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class VersionInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_version=None, model_version=None):  # noqa: E501
        """VersionInfo - a model defined in OpenAPI

        :param api_version: The api_version of this VersionInfo.  # noqa: E501
        :type api_version: str
        :param model_version: The model_version of this VersionInfo.  # noqa: E501
        :type model_version: str
        """
        self.openapi_types = {
            'api_version': str,
            'model_version': str
        }

        self.attribute_map = {
            'api_version': 'api_version',
            'model_version': 'model_version'
        }

        self._api_version = api_version
        self._model_version = model_version

    @classmethod
    def from_dict(cls, dikt) -> 'VersionInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VersionInfo of this VersionInfo.  # noqa: E501
        :rtype: VersionInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_version(self) -> str:
        """Gets the api_version of this VersionInfo.


        :return: The api_version of this VersionInfo.
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version: str):
        """Sets the api_version of this VersionInfo.


        :param api_version: The api_version of this VersionInfo.
        :type api_version: str
        """
        if api_version is None:
            raise ValueError("Invalid value for `api_version`, must not be `None`")  # noqa: E501

        self._api_version = api_version

    @property
    def model_version(self) -> str:
        """Gets the model_version of this VersionInfo.


        :return: The model_version of this VersionInfo.
        :rtype: str
        """
        return self._model_version

    @model_version.setter
    def model_version(self, model_version: str):
        """Sets the model_version of this VersionInfo.


        :param model_version: The model_version of this VersionInfo.
        :type model_version: str
        """
        if model_version is None:
            raise ValueError("Invalid value for `model_version`, must not be `None`")  # noqa: E501

        self._model_version = model_version
