from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ensemble_inference.models.base_model import Model
from ensemble_inference import util


class VotingStrategyEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SOFT = 'soft'
    HARD = 'hard'
    def __init__(self):  # noqa: E501
        """VotingStrategyEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VotingStrategyEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VotingStrategyEnum of this VotingStrategyEnum.  # noqa: E501
        :rtype: VotingStrategyEnum
        """
        return util.deserialize_model(dikt, cls)
